- pkg/pmem-csi-driver/registryserver.go
I don't see fmt.printf messages in log with default setting
so I replace thise with glog.Info. Also, correcting
spelling and wording.
> change logging in registryserver.go

- cmd/pmem-ns-init/main.go
golint points out zero value assignement is redundant,
also delete unused const (leftover) and old comment
about phys device detection which has no real value.
> cmd/pmem-ns-init/main.go: code and comment cleanup

- README-qemu-notes.md
2 emulated NVDIMMs leads to some troubles which are not
seen with 1 DIMM, so let's not advertise this method.
Also, add note about automated VM setup in test/
> README-qemu-notes.md: stop advertising 2 emulated NVDIMMs

- cmd/pmem-ns-init/main.go
- pkg/ndctl/region.go
Namespace creation is simplified and instead of creating fixed
amount of namespaces we calculate, we advance in while-style loop
until all allowed space is used. The last,smaller namespace will use
all remaining space, thus solving unused-leftover problem we had,
also it solves "cant fit 4G into 4G region" risk.
In addition we try tp do it all without hard-coding namespace
overhead. But we start taking account alignement rounding.
Also, this commit adds check for "own" namespace name
if adding up already use space, this check remained missing
in an earlier change when we introduced own vs foreign checks.
> pmem-ns-init/main.go: simplify namespace creation, use leftover

- pkg/ndctl/region.go
We should not reduce the resulting namespace size when
force-aligning it
> ndctl/region.go: force-align upward in Region.CreateNamespace

- Makefile
- cmd/pmem-csi-driver/Dockerfile
- cmd/pmem-ns-init/Dockerfile
- cmd/pmem-vgm/Dockerfile
This change required addition of bash-completion to deps,
and --without-systemd in config options.
> Dockerfiles: advance to ndctl version 63, use single version definition

- cmd/pmem-ns-init/main.go
At some point in creation loop, we typically reach the state
where calculated size remains available but actual available
is zero, so detect this and break, instead of calling
zero-size creation request and breaking loop
based on returned error.
Fixes #125
> pmem-ns-init: Avoid zero-size namespace creation request

- pkg/pmem-csi-driver/nodeserver.go
Removing, creating directory is not duty of this driver.
Stop checking for existing bind-mount, should not be needed.
Stop retrieve of Fstype and log of it's value, this has no meaning in bind-mounting
> nodeserver.go: simplify NodePublish and NodeUnpublish

- cmd/pmem-csi-driver/Dockerfile
We have to support ext4 and xfs file systems. Lack of xfs
utils remained undetected as by default testers use ext4.
Fixes #135
> pmem-csi-driver: add install of xfsprogs in Dockerfile

- Makefile
- cmd/pmem-csi-driver/Dockerfile
- cmd/pmem-ns-init/Dockerfile
- cmd/pmem-vgm/Dockerfile
Instead of repeated flags for configure pass of ndctl,
define flags once in Makefile and pass via build-args parameter.
Also, do not specify those flags which are same with defaults.
> Docker build of ndctl: specify config flags once without defaults

- pkg/pmem-csi-driver/registryserver_test.go
In reset change 911d0b97fb4308fabf8d076012b9e3a95a40b9b6, where Capacity field in
RegisterControllerRequest is removed. This needs fixes to registry tests.
> Fix to test failure

- test/test.make
Not all systems accept old-style tail +N option,
result will be failure opening file:+2 and
showing 10 lines from file we wanted.
P.S. seems my editor added newline as complimentary fix
> test fixes: don't use old-style tail +N option

- test/setup-ca-kubernetes.sh
- test/start-stop.make
There were various issues:
- kubectl had to be available on the host: replace with invoking
kubectl via ssh inside the VM
- a race condition between starting the signing and retrieving the
result, leading to an empty .crt file and then a validation error
from kubectl (unknown object type "nil"): added a while loop
- errors were ignored: now it runs with -e
- some typos and extra spaces and newlines
> test: fix and enhance setup-ca-kubernetes.sh

- test/test.make
- vendor-bom.csv
The ordering of text files is locale-specific. When comparing against
the reference files we have to ensure that the same ordering is used
regardless of the environment and/or the actual "sort" implementation.
LC_ALL=C ensures that for GNU sort and glibc. LANG=C is added just as
an extra precaution for other implementations.
> test: used fixed sort order

- test/e2e/storage/csi_volumes.go
This reduces e2e test failure count 4->3
We may consider using symlinks in deploy/ directory instead of explicit path
which we have to maintain then in sources, but as elsewhere already kubernetes-1.13 was used,
I continue same style here.
> test/e2e: use kubernetes-1.13 path for manifest

- test/e2e/storage/sanity.go
Due to recent rename of dynamically created pods,
this Wait should be checking pmem-csi-unified-0 instead
of pmem-csi-controller-0. This change reduces
amount of "connection refused, reconnecting" errors.
> test/e2e: wait for pmem-csi-unified-0 in BeforeEach

- test/test.make
This avoids test results caching which does not make sense
in e2e case where dependencies are not well locally determined.
> test.make: add -count=1 to go test in e2e case

- Makefile
- cmd/pmem-csi-driver/Dockerfile
- cmd/pmem-ns-init/Dockerfile
- cmd/pmem-vgm/Dockerfile
Also, some streamlining in ndctl build deps definition, so that we can define
those once instead of three replicas that we had previously
Fixes #163
> advance to ndctl version 64

- pkg/pmem-csi-driver/nodeserver.go
Lack of this check causes failure with newest csi-sanity
Fixes: #185
> NodeStageVolume: check for VolumeCapability in request

- pkg/pmem-device-manager/pmd-lvm.go
Some log messages were relevant in early prototyping days
and do not add value any more, like which Bus and Region
we walk in loop.
> WIP: clean and reduce logging

- Makefile
- cmd/pmem-csi-driver/Dockerfile
- cmd/pmem-csi-driver/main.go
- cmd/pmem-ns-init/Dockerfile
- cmd/pmem-ns-init/main.go
- cmd/pmem-vgm/Dockerfile
- cmd/pmem-vgm/main.go
- pkg/pmem-csi-driver/pmem-csi-driver.go
Setting driver version from $(git describe). Currently this version is not
generated from "tags", which should be fixed once we have release tagging.
All driver commands have "-version" flag which shows the current version and
exits.
FIXES #183
> Implement release versioning

- deploy/kubernetes-1.13/pmem-csi-direct.yaml
- deploy/kubernetes-1.13/pmem-csi-lvm.yaml
cluster-driver-registrar sidecar needs to "create/delete" csidrivers hence need
these RBAC rules.
> fix deployment RBAC rules

- cmd/pmem-csi-driver/main.go
- deploy/kubernetes-1.13/pmem-csi-direct.yaml
- deploy/kubernetes-1.13/pmem-csi-lvm.yaml
- deploy/kubernetes-1.13/pmem-storageclass-cache.yaml
- deploy/kubernetes-1.13/pmem-storageclass.yaml
- deploy/kubernetes-1.13/pmem-unified-csi.yaml
- pkg/pmem-csi-driver/pmem-csi-driver.go
As per CSI specification plugin name should include plugin's host company name
and the plugin name. And it must follow domain name notation format.
Hence set default plugin name to 'pmem-csi.intel.com', which can be altered
using -driverName command-line argument.
> Set default driver name to pmem-csi.intel.com

- pkg/pmem-csi-driver/pmem-csi-driver.go
- pkg/pmem-csi-driver/registryserver.go
Instead of exiting with error, driver has to wait and retry 'node controller'
registration till the registry server up and registration get succeed.
FIXES: #182
> Keep retry registering node controller with RegistryServer

- deploy/kubernetes-1.13/pmem-csi-direct.yaml
Bidirectional was accidentally copy-pasted in original
version of that file, it may potentially cause
some side effects propagating state from container to host /dev
so we should not have it there.
Pass of /sys is vital for direct mode to work. This was
tested and tuned in e2e tests which uses another deployment
file, so it was never carried over here, but it is needed.
> Direct-mode deploy example: no Bidirectional, use /sys

- README.md
The plus sign leads to a special link target that pandoc doesn't seem
to handle correctly. To avoid that issue in the future, let's use
"QEMU and Kubernetes" as section title.
This fixes https://github.com/intel/pmem-CSI/pull/191/commits/5321c4e879a7c5f1fc5055a2fe086e03fa97cc3d#r266401518
> README.md: fix QEMU + Kubernetes link

- test/e2e/storage/pmem_csi.go
- test/setup-clear-kvm.sh
We had broken RBAC rules in one of the previous PRs and didn't notice because `cluster-driver-registrar` continued running and we didn't have tests for it's expected behavior.
This PR adds such a test and also updates the CRD installation.
> crd installation + test

- README.md
Previous text repeated almost same thing twice, and telling
about labeling need _after_ example command is misleading,
giving wrong idea that something more needs to be done.
Change node name in labeling example to be template.
> README: simplify text describing node labeling

- deploy/kubernetes-1.13/pmem-csi-direct.yaml
- deploy/kubernetes-1.13/pmem-csi-lvm.yaml
- deploy/kubernetes-1.13/pmem-unified-csi-lvm.yaml
Reduce diff between LVM and Direct variants for clarity.
Use terminationPath clause and deviceManager option in node part
only as these are relevant only in mode=node case.
Give deviceManager option in both deviceMode files for clarity.
> Deploy examples: Clean and streamline LVM vs Direct files

- README.md
If a user does not use 'make start' method, driver deployment
will fail by steps because steps don't mention certs setup.
Resolves #194
> README.md: mention need to set up certificates in Setup section

- README.md
- deploy/kubernetes-1.13/pmem-app.yaml
- deploy/kubernetes-1.13/pmem-pvc.yaml
- deploy/kubernetes-1.13/pmem-storageclass.yaml
Using two volumes serves multiple purposes:
- makes use and demonstrates configuration of ext4 vs xfs formats
- stresses driver more as 2 creations on same node go in parallel
Note that in storageclass we change
volumeBindingMode from Immediate to WaitForFirstConsumer
to make deployment work for two volumes
> Use two volumes instead of one in deploy example

- pkg/pmem-device-manager/pmd-lvm.go
- pkg/pmem-device-manager/pmd-ndctl.go
- pkg/pmem-device-manager/pmd-util.go
When two volumes are requested at once, Creation typically
causes two parallel Creation calls to run, and without
mutex locking we will run into troubles.
Fixes #205
> WIP: Add mutex lock around device-oriented operations

- pkg/pmem-csi-driver/controllerserver-node.go
Fixed typo in in error checking while parsing bool value.
Also made more verbose in case of parsing failures.
FIXES #220
> Fix issue in parsing "eraseafter" parameter

- deploy/kubernetes-1.14
- test/setup-clear-kvm.sh
First change:
Kubernetes 1.14 brings output change, join command example
is printed on two lines separated by `\` which is
problematic for grep. Join all multi-lines before grep
using sed. Currently there is just this one.
> Support test on 1.14 cluster

- README.md
Some labels, for example pmem-csi.intel.com/node=, are added
to nodes only if certain feature gates are active,
makes it too easy to miss. Let's have a step checking labels.
> README: add verify labels step in "run in cluster" section

- pkg/pmem-csi-driver/nodeserver.go
It appears newer kernels refuse to use dax on LVM-exposed
block device if formatted ext4 file system uses 1k block
which is selected heuristically by mkfs.ext4 for smsller volumes.
e2e test code uses specifically small volumes and tests do fail.
Fixes #225
> nodeserver.go: Use hard-coded 4096 block size in mkfs.ext4 and mkfs.xfs

- README.md
We can not verify both important labels before deploying
driver, because node= label is given when driver starts.
Note, this moves text block without changing it.
> README: Move "Verify node labels" block after "Deploy driver" block

- deploy/kubernetes-1.13/pmem-csi-lvm.yaml
- deploy/kustomize/kubernetes-1.13-lvm/lvm-patch.yaml
Deployment failed in CRIO case in LVM mode because of
read-only /sys. This change makes it work.
> Deployment: add explicit /sys mount in pmem-ns-init in LVM mode

- pkg/ndctl/ndctl.go
- pkg/ndctl/region.go
- pkg/pmem-device-manager/pmd-ndctl.go
This simplifies the use of Align variable, as most
of it's use, including use in downward API to libndctl,
uses 64 bit value, so we can get rid of many typecasts.
This also avoids integer overflow error that is caused
by using 32-bit value in intermediate variable.
Resolves #244
> Change NamespaceCreation opts.Align to be 64-bit value

- deploy/kubernetes-1.13/pmem-csi-lvm-testing.yaml
With some changes applied from commits in a branch
while kustomized changed came in another, generated
parts ended up out of sync. This make them up-to-date.
> Fix kustomize-generated parts to be in sync again

- Makefile
- README.md
- test/clear-kvm.make
- test/setup-clear-kvm.sh
- test/start-stop.make
- test/start_qemu.sh
- test/test.make
This was originally based on PR #238, but I ended up doing it differently: instead of just renaming files in `_work`, files related to a cluster installation are now in `_work/clear-kvm[-something]` sub-directories, with generic names inside that directory.
The immediate benefit is that multiple parallel clusters can prepared in parallel (but cannot run in parallel yet).
When we add alternative ways of bringing up clusters, we can just swap out the rules which set up the cluster, while code using the cluster just needs to know the directory name and then can use the generic files inside it for whatever operation it needs to do (to be decided).
> better cluster filenames

- deploy/kubernetes-1.13/pmem-csi-direct-testing.yaml
- deploy/kubernetes-1.13/pmem-csi-direct.yaml
- deploy/kubernetes-1.13/pmem-csi-lvm-testing.yaml
- deploy/kubernetes-1.13/pmem-csi-lvm.yaml
- deploy/kustomize/kubernetes-1.13/kustomization.yaml
One deployment trial case shows that driver deployment fails with version 1.0.2 but succeeds with 1.1.0.
In failing case, node-driver-registrar fails in getting connection to local csi socket, times out in 60s, and causes pod to exit and CrashLoop. For some reason (still not explained), this scenario repeats multiple times.
There is explanation why connection can take longer time 1st time, because node driver is in turn waiting to register with controller, and controller is still in starting stage.
But such wait should not happen on 2nd start of node pod.
In 1.1.0 the timeout and exit was removed and driver-registrar keeps trying. That seems to help
in the current deployment case.
> Advance csi-node-driver-registrar version to 1.1.0

- cmd/pmem-ns-init/main.go
- cmd/pmem-ns-init/main_test.go
- pkg/pmem-csi-driver/registryserver_test.go
- test/test.make
Instead of setting sane values if out-of-bounds values found,
return error and fail the program with error msg.
Work in progress, dont merge yet.
Unit testing of argument values can be added here in same PR.
Resolves #223
> add args unit tests for pmem-ns-init, other minor unit testing improvements 

- test/setup-clear-kvm.sh
- test/test-config.sh
This is useful when there are additional local registries that don't
have an SSL certificate that Clear Linux trusts out-of-the-box.
> test: set up cluster with additional insecure registries

- cmd/pmem-csi-driver/main.go
- deploy/kubernetes-1.13/pmem-csi-direct-testing.yaml
- deploy/kubernetes-1.13/pmem-csi-direct.yaml
- deploy/kubernetes-1.13/pmem-csi-lvm-testing.yaml
- deploy/kubernetes-1.13/pmem-csi-lvm.yaml
- deploy/kubernetes-1.14/pmem-csi-direct-testing.yaml
- deploy/kubernetes-1.14/pmem-csi-direct.yaml
- deploy/kubernetes-1.14/pmem-csi-lvm-testing.yaml
- deploy/kubernetes-1.14/pmem-csi-lvm.yaml
- deploy/kustomize/driver/pmem-csi.yaml
- deploy/kustomize/patches/direct-patch.yaml
- pkg/pmem-csi-driver/pmem-csi-driver.go
Write termination message to TERMINATION_MESSAGE_PATH
The path is different from default /dev/termination-log
because we need to pass /dev/ explicitly to containers,
and that is known to cause container creation failure
if combined with termination-log located on /dev.
So we relocate termination log to /tmp.
We define env.var that we pass into container so that
container knows where to create the termination message.
Resolves #233
> Write termination message to TERMINATION_MESSAGE_PATH

- deploy/kubernetes-1.13/pmem-csi-direct-testing.yaml
- deploy/kubernetes-1.13/pmem-csi-direct.yaml
- deploy/kubernetes-1.13/pmem-csi-lvm-testing.yaml
- deploy/kubernetes-1.13/pmem-csi-lvm.yaml
- deploy/kubernetes-1.14/pmem-csi-direct-testing.yaml
- deploy/kubernetes-1.14/pmem-csi-direct.yaml
- deploy/kubernetes-1.14/pmem-csi-lvm-testing.yaml
- deploy/kubernetes-1.14/pmem-csi-lvm.yaml
- deploy/kustomize/driver/pmem-csi.yaml
This option has been deprecated and has no effect.
> Delete provisioner= option from external-provisioner deployment

- Makefile
Dependency tracking was meant to avoid "make kustomize" from
doing unnecessary work. But because the output files are under git
control, "git rebase" can lead to an inconsistent state (output files
out-dated, but were touched last by git). It's better to always
re-generate them.
Also fixes the .PHONY declaration of the other targets.
> kustomize: always rerun operations

- Makefile
- cmd/pmem-csi-driver/Dockerfile
- cmd/pmem-ns-init/Dockerfile
- cmd/pmem-vgm/Dockerfile
Dockerfiles: invalidate cache before "swupd update"
Docker caches previous build results and skips commands that it has
executed in the same context before. The result is that the "swupd
update" command may get skipped during a build:
```    
Step 6/33 : RUN swupd update && swupd bundle-add ${NDCTL_BUILD_DEPS} go-basic-dev && rm -rf /var/lib/swupd
---> Using cache
---> 229de2b1ee2e
``` 
That caching defeats the purpose of the command, which is to ensure
that all the latest updates for the base image are getting applied.
On the other hand, not using a cache at all (= "docker build
--no-cache") would slow down developers a lot (> 20min build times).
The solution is to invalidate the cache right before the "swupd
update" command by injecting an unused "CACHEBUST" variable, as
described in …
> Dockerfiles: invalidate cache before "swupd update"

- README.md
With resent change #271, now we build single image and make targets
{build,push}-images are not valid, instead one should use {build,push}-image.
> README.md: Changes to build steps as per new image changes

- test/start-stop.make
Insufficient quoting around the inline shell comment caused the shell
to invoke "ndctl" on the host.
> test: fix garbage 'ndctl: command not found' output

- runtime-deps.csv
- test/test.make
The additional IDs for Go and Kubernetes help when checking the status
of these projects in the Intel-internal tooling. Kubernetes-CSI can be
considered part of Kubernetes and doesn't need an extra entry.
> runtime deps: Go and Kubernetes updates

- Dockerfile
- Makefile
Docker image building might fail if one tries to build directly without using
our defined make targets. In this case, as the mandatory NDCTL* build args have
no default values that result in unexpected build failures.
With this change, Dockerfile is self-contained and uses these defaults defined
in Dockerfile.
> Dockerfile: Provide defaults for build args

- test/setup-ca-kubernetes.sh
Add check to throw a warning and exit in case of no nodes with "storage=pmem"
label.
Took the opportunity to improve the script, such that now it generates secrets
only for newly added nodes. First, it retrieves existing node secrets and
filters out those nodes from all pmem nodes and generates certificates for
leftover nodes.
Now one can add new pmem node(node with storage=pmem label) and rerun the script
for generating secrets for that new node, ever after deploying the driver.
Fixes: #272
> setup-ca-kubernetes.sh: Handle no pmem nodes case

- Dockerfile
Use ldconfig to create the necessary links and cache to the most recent shared libraries
Note: This should not really be needed, but resolves the issues on machine where we face this issue.
Fixes: #293
Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>
> Dockerfile: Use ldconfig to create the necessary links

- pkg/pmem-device-manager/pmd-util.go
Format error was introduced by accident with previous commit.
Also, improved comment wording, and deleted part of comment
which was confusing and did not add much value.
> pmem-device-manager/pmd-util.go: correct format error

- Makefile
On a clean checkout or after "make clean", "make test" failed with:
make: *** No rule to make target '_work/kustomize', needed by
'test-kustomize-deploy/kubernetes-1.13/pmem-csi-direct.yaml'.  Stop.
That's the result of changing how the kustomize binary is built and
then not adapting all dependencies on it.
> Makefile: fix "make test-kustomize" dependency

- README.md
This used to be part of README-qemu-notes.md, which was removed
because it seemed obsolete. But labeling is still needed in virtual
machines.
> README.md: PMEM preparation in VMs

- Dockerfile
- hack/update-clear-linux-base.sh
Before tagging a release, we want to ensure that the image for that
release can always be reproduced from source. For that we need to lock
down:
- the Clear Linux base image
- the version we update to
The intended usage is:
1. create a release branch
2. run this script on the branch, commit
3. test
4. tag
5. repeat at step 2 regularly to produce an up-to-date release image
> release: support reproducible builds

- pkg/pmem-csi-driver/controllerserver-master.go
- pkg/pmem-csi-driver/controllerserver-node.go
- pkg/pmem-csi-driver/pmem-csi-driver.go
- pkg/registryserver/registryserver.go
- pkg/registryserver/registryserver_test.go
When nodes register, there is a race condition around the concurrent
modifications and/or usage of the node info map by the master
controller. All accesses to that field have to be protected by a
mutex.
To enforce this, the RegistryServer implementation gets moved into its
own package with only those methods exported which do proper
locking.
Fixes: https://github.com/intel/pmem-CSI/issues/226
> pmem-csi-driver: fix race condition in registry server

- Jenkinsfile
29980 too often failed to restart Kubernetes because
Docker forgot about the containers after a restart.
> Jenkinsfile: go back to Clear Linux 29820

- pkg/pmem-grpc/grpc.go
- test/e2e/storage/sanity.go
- Often test failures such as #322 are caused by delay the Node driver knowing about the connection failures to Controller. This PR resolves this by adding Keepalives to grpc connections.
> Fixes to test failures

- test/e2e/storage/sanity.go
The following error occurred randomly:
rmdir: '/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pmem-sanity-target.ECDAPN': No such file or directory
Most recently it was observed in the teardown after an otherwise
successful node restart test. One possible reason is that the
directory was created before the test ran, but never got flushed to
disk, so when the node came back up, the directory was lost.
We may be able to avoid that by explicitly syncing. This is done only
in those tests which need it and at the very beginning, so changes
made by the driver still need to be synced by the driver itself.
> test: sync filesystem before starting restart tests

- Dockerfile
Change 5c5f60601246865220eeb63ecb7eba7c63f3e15d introduced 3-phase image
building, in that VERSION argument spans to different(base & binaries) phases.
This makes VERSION passed via Makefile(build-arg) is not reached properly.
This change fixes this by moving the VERSION argument to appropriate phase.
> Dockerfile: Fix missing image version issue

- Makefile
Some previous change moved the location of the version string from the
"main" package into "pkg/<binary>". The build rules were adapted for
the testing variant of the binaries, but not the production variant.
> Makefile: properly set version string in production binaries

- pkg/pmem-csi-driver/controllerserver-master.go
- pkg/pmem-csi-driver/controllerserver-node.go
Controller shall not ignore errors reported by node while deleting volumes.
Instead, It shall report back the failure to caller/external-provisioner.
FIXES: #329
> pmem-csi-driver: Do not ignore DeleteVolume failures on node

- test/start-kubernetes.sh
The download_image function is called with redirected stdout because
that's where it reports the image to be used. That means that error
messages must be sent to stderr (which is good practice anyway),
otherwise they are not visible to the user.
> test: fix image verification error

- Dockerfile
- pkg/pmem-device-manager/pmd-lvm.go
- pkg/pmem-device-manager/pmd-util.go
- test/e2e/storage/cleanup.go
- test/e2e/storage/csi_volumes.go
- test/e2e/storage/sanity.go
Often LVM stress tests are failing due to race conditions in executing LVM operations.
Hence, we added mutex locking so that only one LVM operation is in progress.
As part of this also made changes to cache LVM volumes by device manager so that it avoids repeated lvs calls.
This is an alternative approach to #334 to attack the lvm issues
> DeviceManager/LVM: Synchronize all lvm calls

- pkg/pmem-device-manager/pmd-util.go
There is code path where a volume that remained mounted, gets
erased by shred. This has happened for various reasons, like
incorrect paths use by tester code.
Detect that the device is opened, and return error before
performing shred, avoiding unnecessary destruction that
would show as garbage remaining mounted as file system.
Resolves: #317
Resolves: #338
> Refuse to clear mounted device

- test/e2e/storage/sanity.go
/tmp is not guaranteed to reside on tmpfs-type file system,
it is part of rootfs on multiple distros (CentOS, Ubuntu etc).
Resolves #325
> RestartNode: use /run for temp.file instead of /tmp

- pkg/pmem-csi-driver/nodeserver.go
In debugging of stress test logs, it was noticed that
log message about umount is misleading, as the function may
return after logging "unmount" without actually unmounting,
Move the log message to happen after possible skip,
also add message about skipping the umount as it may become
useful information.
Resolves #339
> NodeUnPublish: move log msg after skip point, add skip log

- test/e2e/e2e.go
- test/e2e/storage/sanity.go
- test/e2e/wrapper.go
Addresses two issues seen by @okartau when testing on real hardware:
- failure not logged
- failure not captured by GinkgoRecover
The problem itself most likely was an error during directory setup or teardown. That can still happen, but now it should be visible.
The problem itself might have been the "126 = cannot execute error" that I also got in a CI run. Workaround for that also included.
> failure handling

- pkg/pmem-device-manager/pmd-lvm.go
- pkg/pmem-device-manager/pmd-ndctl.go
- pkg/pmem-device-manager/pmd-util.go
With recent change #6a8d1ee6b9ee4ba371730a23e363ad7589c11908 FlushDevice()
itself handles the mutex(volumeMutex) locking and unlocking, so
callers(LVM,ndctl) should not lock explicitly while calling this utility method.
> DeviceManager/ndctl: Fix deadlocking

- Jenkinsfile
- deploy/kubernetes-1.13/pmem-csi-direct-testing.yaml
- deploy/kubernetes-1.13/pmem-csi-direct.yaml
- deploy/kubernetes-1.13/pmem-csi-lvm-testing.yaml
- deploy/kubernetes-1.13/pmem-csi-lvm.yaml
- deploy/kubernetes-1.14/pmem-csi-direct-testing.yaml
- deploy/kubernetes-1.14/pmem-csi-direct.yaml
- deploy/kubernetes-1.14/pmem-csi-lvm-testing.yaml
- deploy/kubernetes-1.14/pmem-csi-lvm.yaml
- deploy/kustomize/kubernetes-1.13/kustomization.yaml
- deploy/kustomize/kubernetes-1.14/kustomization.yaml
- deploy/kustomize/patches/external-provisioner-connection-timeout-patch.yaml
- deploy/kustomize/patches/external-provisioner-timeout-patch.yaml
- test/e2e/storage/csi_volumes.go
- test/start-kubernetes.sh
This changes the test setup such that the CI covers LVM and direct mode on Kubernetes 1.14.
> test direct mode and LVM

- test/start-kubernetes.sh
This reverts commit 7dddc7158611fdaa7919c53d0e93628ce3aaff56.
Test flakiness in the CI seems to have increased, potentially because
of that commit.
> Revert "test: reduce size of VM cluster"

- test/setup-ca-kubernetes.sh
The the format for the existing_secrets variable was not right, caused
to not find the nodes with the pmem-csi-node-secrets correctly. Removed
unnecesary quotes and whitespaces.
Signed-off-by: Gabriel Briones <gabriel.briones.sayeg@intel.com>
> Bugfix setup-ca-kubernetes.sh script

- pkg/ndctl/region.go
- pkg/pmem-csi-driver/controllerserver-node.go
- pkg/pmem-device-manager/pmd-lvm.go
- pkg/pmem-device-manager/pmd-ndctl.go
- pkg/pmem-ns-init/main.go
Stop doing aligning on 2 layers, only do it in ndctl
and align rounding up there. In pmem-device-manager
layer make sure that size what we ask is at least 2GB.
Adding "get interleve ways" function in ndctl layer so that
namespace creation function can adjust to real alignment value.
Resolves #348
> Better alignment handling

- test/e2e/storage/sanity.go
- test/test.make
The small volume size gets rounded up considerably, which makes test
execution noticably slower than for LVM mode. To get back to acceptable
execution times we create less volumes.
> test: reduce sanity stress test size of direct mode

- pkg/pmem-grpc/grpc.go
This is trivial fix to double log issue,
better one can also be made.
Resolves #356
> Reduce "Connecting to" redundant log

- .dockerignore
- Makefile
In our Dockerfile we only need the Go source code, make rules and
configuration files. By explicitly selecting those we can cut down the
amount of data sent to the Docker daemon from 120MB to 56MB.
Another advantage is that changes to other files no longer invalidate
the Docker cache for "ADD ." because the modified files are not
included.
> build: limit Docker context to files that are needed

- pkg/pmem-csi-driver/controllerserver-master.go
Driver does not support Block mode of access_type,
so we have to return not-supported for such request.
Same check also in Validation method.
Resolves #353
> Check for Volume Capability.access_type

- Jenkinsfile
- Makefile
This idea originally came up when the private registry was introduced
and a search then showed that this has indeed been done before
(https://andrewlock.net/caching-docker-layers-on-serverless-build-hosts-with-multi-stage-builds---target,-and---cache-from/):
with `--cache-from` we can use existing images to warm up the Docker
build cache. This keeps the Dockerfile and thus normal developer
workflow simple (no need to manually build base images first) while
making the CI faster.
The we get the most benefit out of caching the build image, but
pulling the PMEM-CSI driver image is also worthwhile. When doing both
and nothing changed, the two image build stages take ~8min instead of
~19min.
Only the non-PR jobs push build images. PR jobs pick up those images
and use the same cachbust value. …
> CI caching

- Dockerfile
An ARG instruction goes out of scope at the end of the build stage where it was
defined. To use an arg in multiple stages, each stage must include the ARG
instruction.
Refer to:
https://github.com/docker/cli/blob/master/docs/reference/builder.md#understand-how-arg-and-from-interact
FIXES: #382
> Dockerfile: Redefine SWUPD_UPDATE_ARG in all build stages.

- Dockerfile
Replace deprecated swupd '-m' option in SWUPD_UPDATE_ARG comments section.
FIXES: #379
> Dockerfile: Remove deprecated option from comments

- README.md
Left-over dash in creation command example makes it unusable.
> README: fix invalid syntax of example deploy command

- Dockerfile
Clear Linux switched to Go 1.13, which currently fails during "make
test" with:
go test -run none ./pkg/... ./test/e2e
...
flag provided but not defined: -test.testlogfile
Usage of /tmp/go-build240487305/b265/e2e.test:
[no -test flags here]
That Go updates depend on code changes is not unusual, it happened
before for example because "go fmt" changed how code gets
formatted. Therefore the version of Go must depend on the PMEM-CSI
code, not the version of Clear Linux.
This can be achieved by downloading the toolchain. As a side effect
the download might be faster.
> build: use fixed Go version

- Dockerfile
The previous commit (bc7f7be004840f9d64ac4d6e58c9083ab560dde6) should
have contained this change here.
Clear Linux switched to Go 1.13, which currently fails during "make
test" with:
go test -run none ./pkg/... ./test/e2e
...
flag provided but not defined: -test.testlogfile
Usage of /tmp/go-build240487305/b265/e2e.test:
[no -test flags here]
That Go updates depend on code changes is not unusual, it happened
before for example because "go fmt" changed how code gets
formatted. Therefore the version of Go must depend on the PMEM-CSI
code, not the version of Clear Linux.
This can be achieved by downloading the toolchain. As a side effect
the download might be faster.
> build: use fixed Go version, part II

- pkg/pmem-csi-driver/controllerserver-master.go
Use hash value of Volume Name in request as VolumeID, instead
of creating a new UUID each time a request arrives,
This avoids situations where different VolumeIDs may be associated
with same name.
Resolves: #404
> Controller: Create VolumeID from name as hash function

- deploy/kubernetes-1.13/pmem-csi-direct-testing.yaml
- deploy/kubernetes-1.13/pmem-csi-direct.yaml
- deploy/kubernetes-1.13/pmem-csi-lvm-testing.yaml
- deploy/kubernetes-1.13/pmem-csi-lvm.yaml
- deploy/kubernetes-1.14/pmem-csi-direct-testing.yaml
- deploy/kubernetes-1.14/pmem-csi-direct.yaml
- deploy/kubernetes-1.14/pmem-csi-lvm-testing.yaml
- deploy/kubernetes-1.14/pmem-csi-lvm.yaml
- deploy/kustomize/driver/pmem-csi.yaml
- deploy/kustomize/testing/socat.yaml
/var/lib/kubelet/{plugins,plugins_registry} is the location for plugins which
are supposed to implement kubelet's plugin registration API. This is implemented
by node-driver-registrar sidecar container in case of a CSI driver.
So PMEM-CSI should not use these locations for creating its listening socket.
No we use plugin state directory(/var/lib/pmem-csi.intel.com) for this.
Fixes: #394
> deploy: Do not use kubelet plugins location for driver socket

- pkg/pmem-device-manager/pmd-lvm.go
LVM device manager caches the devices that it creates, but not cleaning up those
device references on delete. This change fixes this issue.
> DeviceManager/lvm: Remove device from cache on delete

- Dockerfile
When running in the CI, we have the "error loading libraries" error
again because the "ldconfig" workaround came after using curl.
> Dockerfile: fix curl "error loading libraries" error in CI

- Jenkinsfile
This implements the policy described in
https://github.com/intel/pmem-csi/blob/devel/DEVELOPMENT.md#branching:
each time full testing of the "devel" branch has succeeded, "master"
gets moved forward to it.
> CI: automatic update of master branch

- Jenkinsfile
- test/setup-fedora-govm.sh
- test/setup-kubernetes.sh
- test/start-kubernetes.sh
- test/test-config.sh
We see timeouts between VMs and network issues. The etcd container log provided the smoking gun: etcd IO was taking too long. Putting it's data into a ramdisk solved that.
Together with a retry-loop for Fedora downloads the CI is now stable and faster than before thanks to the tuning of the number of CPUs: https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/job/pmem-csi/view/change-requests/job/PR-426/
> CI: performance monitoring + improvements

- Makefile
- test/start-kubernetes.sh
docker push" has been seen to fail temporarily with "error creating
overlay mount to /var/lib/docker/overlay2/xxx/merged: device or
resource busy".  To increase the chance of the CI builds completing,
we simply try three times before giving up.
> build: retry 'docker push'

- test/setup-kubernetes.sh
Fixes two problems:
- Feature gates not set for control plane components, which prevented pod tests from running on Kubernetes 1.13 where "skip attach" was alpha and thus by default enabled; we rely on that feature. We didn't have proper tests for that, but now we do and full CI testing fails for "devel".
- Kubernetes version not completely locked down (not nice, but not critical at this time).
> cluster setup fix

- Makefile
https://github.com/intel/pmem-csi/pull/430 unintentionally disabled
the make dependencies. That was used during debugging and shouldn't
have been included in the PR.
> build: restore automatic building of images during 'docker push'

- Jenkinsfile
- test/e2e/e2e.go
- test/test.make
We have to run with a custom reporter in order to write JUnit
files. This will be useful for reporting in the CI what tests we ran.
While at it, add TEST_E2E_FOCUS and fix TEST_E2E_SKIP (variable was
spelled wrong).
> CI: enable JUnit output, enhance and fix TEST_E2E make parameters

- Jenkinsfile
Jobs timings have differences that are not easy to understand, for example why "Create Build Env" sometimes takes 4 and some other time 17 minutes.
Seeing timestamps of CI is overall useful IMHO, so lets see does that clause activate those.
> Jenkinsfile: add timestamps option

- Jenkinsfile
A trailing dot is needed to ensure that the test name is treated as
top-level package and is shown directly by the UI.
> CI: enhance JUnit output

- test/e2e/storage/csi_volumes.go
In commit 2e9fde49, we dropped support for v1.13, but tests are still pointing to
storage class files in deploy/kubernetes-1.13. This change fixes this by
pointing to deploy/common.
> test: Remove leftover traces of Kubernetes 1.13

- README.md
- deploy/common/pmem-app-block-volume.yaml
- deploy/common/pmem-pvc-block-volume.yaml
- deploy/kubernetes-1.14/pmem-app-block-volume.yaml
- deploy/kubernetes-1.14/pmem-pvc-block-volume.yaml
- pkg/pmem-csi-driver/controllerserver-master.go
- pkg/pmem-csi-driver/nodeserver.go
- test/e2e/storage/csi_volumes.go
- test/test-config.sh
> Adding support for block volumes

- Jenkinsfile
The recently added increased logging made the resulting
log files rather large, which is a problem when downloading
them and exhausted available space in the Jenkins master.
Now that extra logging is turned off by default respectively
done less frequently (top and df run once a minute). To enable
logging, edit the pipeline in a PR or in the Jenkins UI.
> CI: no logging by default

- Jenkinsfile
- test/e2e/storage/csi_volumes.go
What matters for Jenkins seems to be the classname. By turning
that into <testrun>.<first word of test> we get a nicer grouping.
> set classname in junit file to group tests

- pkg/pmem-csi-driver/controllerserver-node.go
- pkg/pmem-device-manager/pmd-lvm.go
- pkg/pmem-device-manager/pmd-manager.go
- pkg/pmem-device-manager/pmd-ndctl.go
pmd-lvm.go: Delete old irrelevant comments about selection strategy.
LVM uses byte-aligned size arg instead or MB
In CSI spec, Name and VolumeID are different things.
In PMEM-CSI we use VolumeID for naming volumes and namespaces,
so let's stick to the style and use VolumeID in code,
otherwise it may be confusing why we suddenly switch back to "Name"
when code gets down to device-manager level.
> cleaned alignment code, unified naming to use VolumeID more

- test/e2e/storage/sanity.go
On a system where interactive ssh session emits banner,
like Ubuntu, the present ssh cmd run method would fail,
as response would contain banner + "hello",
so lets do it in one command.
Remove also extra "sh -c" as ssh already runs shell.
Resolves: #434
> test/e2e/storage/sanity.go: use single ssh cmd instead of session

- DEVELOPMENT.md
Seems 'go test' is not runnable any more with go 1.11.
Is this right way documenting?
Should we perhaps change earlier stmt about gofmt as well?
We can add some other doc changes to this PR if we get some good ideas.
> DEVELOPMENT.md: document 'go test' requires go 1.12 or newer

- test/e2e/storage/csi_volumes.go
This also requires to change claim size from 1MB to 110 MB,
otherwise files created by test will not fit (needs 102 MB).
As we now have local kubectl installed during testing, we can enable volumeIO tests.
Later after upstream gets kubectl-avoidance change merged,
we will try to stop installing kubectl locally and see does testing still work.
> test/e2e/storage/csi_volumes.go: Enable VolumeIO test suite

- Jenkinsfile
After enabling some more tests, successful runs of the production jobs
are very close to the timeout (29min with a 30min limit). That caused
aborted builds in some cases.
> CI: bump timeouts for production jobs

- test/e2e/storage/latebinding.go
- test/e2e/storage/sanity.go
- test/test.make
test/ was left out of gofmt checking and some formatting
errors have been slipped in there.
> test/test.make: add test/ to gofmt checking path set

- .dockerignore
- Dockerfile
- hack/copy-modules-license.sh
Because both PMEM binaries and the Go toolchain were installed into
/go and the runtime image contained all of /go/bin, we ended up also
copying the Go toolchain.
License files for everything that goes into our /usr/local are
important. 3-clause BSD requires that the copright notice is
reproduced in "other materials provided with the distribution", which
we comply with by copying the license file and its copyright remark
into the image.
hack/copy-modules-license was originally developed for
https://github.com/intel/intel-device-plugins-for-kubernetes/pull/232
and adapted to PMEM-CSI here (multiple packages, no dependency on "go
mod", etc.)
> images: fix content of /usr/local

- hack/verify-vendor.sh
- test/test.make
Ensure that go.mod, go.sum and vendor are up-to-date.
> Go vendor test

- deploy/kubernetes-1.16/pmem-pvc-cache.yam
Change 079683d5f177a87fab4af48fa30a847a50e61907 added an extra unneeded pvc
link, which should be dropped.
> deploy: Remove extra pvc file(link)

- .dockerignore
- DEVELOPMENT.md
- Makefile
- hack/verify-go-version.sh
- test/test.make
Fixes a typo (G0 instad of GO) and adds a warning that tells developers when they are using a different Go version.
> Go version

- test/e2e/storage/sanity.go
Warnings from stderr, for example lvmetad-related warning,
can not be silenced with lvs -q option, and are printed
to stderr. We are not interested in parsing warnings,
so we can consider stdout only, as far as command
execution succeeded.
Resolves #468
> Volume leak test: use ssh Output instead of CombinedOutput

- Jenkinsfile
- go.mod
- go.sum
- pkg/ndctl/ndctl.go
- pkg/ndctl/region.go
- pkg/pmem-csi-driver/controllerserver-master.go
- pkg/pmem-csi-driver/controllerserver-node.go
- pkg/pmem-csi-driver/nodeserver.go
- pkg/pmem-device-manager/pmd-lvm.go
- pkg/pmem-device-manager/pmd-manager.go
- pkg/pmem-device-manager/pmd-manager_test.go
- pkg/pmem-device-manager/pmd-ndctl.go
- pkg/pmem-device-manager/pmd-util.go
- test/e2e/storage/sanity.go
- test/setup-clear-govm.sh
- test/setup-fedora-govm.sh
- test/setup-kubernetes.sh
- test/start-kubernetes.sh
- test/start-stop.make
- test/test.make
- vendor-bom.csv
- vendor/gopkg.in/freddierice/go-losetup.v1/.gitignore
- vendor/gopkg.in/freddierice/go-losetup.v1/LICENSE
- vendor/gopkg.in/freddierice/go-losetup.v1/README.md
- vendor/gopkg.in/freddierice/go-losetup.v1/constants.go
- vendor/gopkg.in/freddierice/go-losetup.v1/device.go
- vendor/gopkg.in/freddierice/go-losetup.v1/format.go
- vendor/gopkg.in/freddierice/go-losetup.v1/info.go
- vendor/gopkg.in/freddierice/go-losetup.v1/losetup.go
- vendor/modules.txt
This PR address a couple of issues:
- Defined new error codes that are returned by DeviceManager interface methods. Made changes to implementations to use these error codes and revised the error messages using error formatting features provided by go-1.13 `fmt` package.
- Discussion on issue #413, raised a requirement that PMEM-CSI should handle the DeleteVolume() call for volumes that the underlined device already deleted manually by the admin.  So for such a volume we just ignore and return no error in DeviceManager.DeleteVolume(). This also makes DeleteVolume() idempotent.
- Issue #402 : CSI.DeleteVolume should return FailedPreCondition error in case of the volume is in use. Test case added for the same.
- Unit tests for device manager
- This PR also contains a commit that removes the …
> Devicemanager: New error codes + Device Manager unit tests and few other fixes.

- README.md
https://github.com/intel/pmem-csi/pull/473 broke the formatting in the "Note about using the sector mode" section.
> README.md: fix formatting

- pkg/pmem-csi-driver/nodeserver.go
NodePublishVolume performs checks for attributes compatibility if volume already mounted.
If StagingTargetPath is not set, return FAILED_PRECONDITION.
Resolves: #462 
Resolves: #465
> Improve NodePublishVolume and NodeStageVolume

- Dockerfile
- Jenkinsfile
- test/start-kubernetes.sh
The recently added vendor check rewrites "vendor" inside Docker, which
later broken working with the repo because those files then became
owned by root.
We could run "sudo chown" after each "docker run" invocation, but it
is safer and faster to not run as root inside Docker in the first
place.
> CI: run under normal user inside Docker

- test/start-kubernetes.sh
Extending NO_PROXY in create_vms only had an effect inside that
subshell. We explicitly need to make that change also in the outer
shell, otherwise kubeadm will fail to reach the API server because the
IP address is not on the exception list.
> test: add individual machines to NO_PROXY

- .dockerignore
- Jenkinsfile
- test/setup-clear-govm.sh
- test/setup-kubernetes.sh
- test/start-kubernetes.sh
- test/test-config.sh
We should better test with a recent Clear Linux. On that release we can also enable "containerd" as runtime.
> update Clear Linux and CRI support

- README.md
- test/start-kubernetes.sh
Not having KVM enabled in a GCE machine is a real issue that a user
ran into. Error handling in this case is poor, GoVM doesn't print any
error and all that the user gets is an error about timing out waiting
for ssh.
The updated README.md explains the real requirements better and warns
about this pitfall. The script itself checks very early for /dev/kvm
and bails out with an error message when it is missing.
> QEMU: enhance documentation and check for /dev/kvm

- Jenkinsfile
- test/setup-kubernetes.sh
- test/start-kubernetes.sh
- test/test-config.sh
- test/test.make
The last remaining reason for requiring sudo and --privileged was that
the scripts themselve set up a tmpfs for etcd. By moving that step out
into the build host we can remove the need for sudo inside the
container.
The etcd volume gets used repeatedly, therefore "mkfs.ext4" must be
forced to ignore an already existing filesystem.
We can switch back and forth between LVM and direct mode on a cluster merely by applying a different deployment. If we run two tests back-to-back which use the same cluster configuration (for example, Fedora with Kubernetes 1.16), then we reuse the existing cluster, which saves around 5 minutes for the second test.
We have some tests marked as '[Slow]': https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/job/pmem-csi/view/change-requests/job/PR-487/32/tes …
> CI: speed up execution

- test/e2e/ephemeral/ephemeral.go
- test/e2e/storage/csi_volumes.go
- test/e2e/storage/dax/dax.go
The tests were failing on Kubernetes 1.14 because ephemeral volumes
aren't supported there.
> test: enable ephemeral test pattern for dax testing only if supported

- Jenkinsfile
- test/setup-kubernetes.sh
- test/start-kubernetes.sh
- test/test-config.sh
- test/test.make
This is a combination of different enhancements which together make pre-merge testing faster. Original PR is https://github.com/intel/pmem-csi/pull/487 which had to be reverted because it caused regression in the "devel" builds.
Changes since then:
```
diff --git a/Jenkinsfile b/Jenkinsfile
index 9f26d685..64320c96 100644
--- a/Jenkinsfile
+++ b/Jenkinsfile
@@ -144,14 +144,15 @@ pipeline {
sh "env; echo Building BUILD_IMAGE=${env.BUILD_IMAGE} for BUILD_TARGET=${env.BUILD_TARGET}, CHANGE_ID=${env.CHANGE_ID}, CACHEBUST=${env.CACHEBUST}."
sh "docker build --cache-from ${env.BUILD_IMAGE} --label cachebust=${env.CACHEBUST} --target build --build-arg CACHEBUST=${env.CACHEBUST} -t ${env.BUILD_IMAGE} ."
// Create a running container (https://stackoverflow.com/a/38308399). We keep it running
- …
```
> CI speedup

- Dockerfile
- deploy/kubernetes-1.14/direct/pmem-csi.yaml
- deploy/kubernetes-1.14/direct/testing/pmem-csi.yaml
- deploy/kubernetes-1.14/lvm/pmem-csi.yaml
- deploy/kubernetes-1.14/lvm/testing/pmem-csi.yaml
- deploy/kubernetes-1.14/pmem-csi-direct-testing.yaml
- deploy/kubernetes-1.14/pmem-csi-direct.yaml
- deploy/kubernetes-1.14/pmem-csi-lvm-testing.yaml
- deploy/kubernetes-1.14/pmem-csi-lvm.yaml
- deploy/kubernetes-1.16/direct/pmem-csi.yaml
- deploy/kubernetes-1.16/direct/testing/pmem-csi.yaml
- deploy/kubernetes-1.16/lvm/pmem-csi.yaml
- deploy/kubernetes-1.16/lvm/testing/pmem-csi.yaml
- deploy/kubernetes-1.16/pmem-csi-direct-testing.yaml
- deploy/kubernetes-1.16/pmem-csi-direct.yaml
- deploy/kubernetes-1.16/pmem-csi-lvm-testing.yaml
- deploy/kubernetes-1.16/pmem-csi-lvm.yaml
- deploy/kustomize/driver/pmem-csi.yaml
- deploy/kustomize/patches/direct-patch.yaml
- deploy/kustomize/patches/lvm-patch.yaml
- deploy/kustomize/testing/args-two-containers-patch.yaml
- deploy/kustomize/testing/args-two-initcontainers-patch.yaml
- deploy/kustomize/testing/controller-coverage-patch.yaml
- deploy/kustomize/testing/lvm-coverage-patch.yaml
- deploy/kustomize/testing/node-coverage-patch.yaml
- test/setup-deployment.sh
It's very annoying that the pmem-csi-driver is marked as entry point
for the pmem-csi-driver image when using it as the container for
running tools that aren't installed on a host, like ndctl or LVM. For
example:
$ docker run --privileged  --rm intel/pmem-csi-driver:v0.5.0 -- ndctl list -Nu
failed to initialize driver: Invalid driver mode: unified
It's better to not specify an entry point and instead select the
command in the deployment. This is then also consistent for all three
commands that we run from the image.
Fixes: #377
> remove entry point for PMEM-CSI image

- pkg/pmem-csi-driver/nodeserver.go
An update of Clear Linux from 32020 to 32050 replaces xfstools 5.0.0
with 5.4.0 and that enables reflink by default. "-o dax" and reflink
are mutually exclusive, so we now have to override the default.
> XFS: disable reflink

- README.md
Fix a mal-formatted link for `kustomize`.
Add a link to the dev docs in the PR/contribution section.
> docs: README: small fixes

- test/test.make
This is useful for -ginkgo.failFast.
> test: support additional e2e.test parameters

- Jenkinsfile
- deploy/kubernetes-1.17
We don't need to change anything for Kubernetes 1.17 except adding a
symlink so that "make start" knows which deployment files to use.
> test Kubernetes 1.17 on Clear Linux 32080

- Jenkinsfile
- test/start-kubernetes.sh
- test/test-config.sh
When the machines don't come up, we need the "docker logs" output to
understand why.
> test: dump docker logs for failed govm cluster

- Makefile
The default IP address for reaching the developer Docker registry
comes from "ip addr show dev docker0" which happens to be a /16
subnet:
```
9: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
link/ether 02:42:79:6d:15:b3 brd ff:ff:ff:ff:ff:ff
inet 172.17.42.1/16 brd 172.17.255.255 scope global docker0
valid_lft forever preferred_lft forever
inet6 fe80::42:79ff:fe6d:15b3/64 scope link
valid_lft forever preferred_lft forever
```
Because the code which extended no_proxy only checked for /24 subnets,
this address 172.17.42.1 was not automatically included.
Reported by @devimc in https://github.com/kata-containers/runtime/issues/2262#issuecomment-575620216.
> test: include docker0 interface address in no_proxy

- Jenkinsfile
- Makefile
- test/setup-fedora-govm.sh
- test/setup-kubernetes.sh
- test/start-kubernetes.sh
Trial to use Fedora-31 cloud image.
In my local setup, after I made these changes, kubernetes setup does not complete on master but fails with timeout. There is kubelet running on master, but networking seems to have problem:
Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady
Let's see does we see same in CI.
> Use Fedora-31 cloud image for testers

- pkg/pmem-common/vgname.go
- pkg/pmem-device-manager/pmd-lvm.go
- pkg/pmem-vgm/main.go
The removal of "fsdax" part in VG names which was made
in connection with "drop sector-mode", introduced
potential API break if VG name was created before change
and used with code after change.
It is safer to put back "fsdax" part of VG name,
it remains hard-coded in all names now, but still
indicates correctly that namespaces are in FSDAX mode.
> Put back "fsdax" as part of VG names

- pkg/pmem-grpc/grpc.go
TLS versions prior to 1.2 are not secure enough, with this change we adjust
minimum supported version in our server/client configuration to 1.2 this
means both registry and node-controller servers authenticate clients
witch supports tls >= v1.2.
This change also disables renegotiation which was discovered as insecure
and easy to exploit.
Below `namp` result ensures that the node controller supports only v1.2 ciphers:
```
$nmap --script +ssl-enum-ciphers -p 10001 172.17.0.4
Starting Nmap 7.60 ( https://nmap.org ) at 2020-02-24 16:09 EET
Nmap scan report for 172.17.0.4
Host is up (0.00021s latency).
PORT      STATE SERVICE
0001/tcp open  scp-config
| ssl-enum-ciphers:
|   TLSv1.2:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
| …
```
> pmem-csi-driver: Set tls.Config minversion to 1.2

- DEVELOPMENT.md
- pkg/ndctl/region.go
- pkg/pmem-csi-driver/controllerserver-master.go
- pkg/pmem-csi-driver/controllerserver-node.go
- pkg/pmem-csi-driver/nodeserver.go
- pkg/pmem-csi-driver/pmem-csi-driver.go
- pkg/pmem-device-manager/pmd-ndctl.go
- pkg/pmem-state/pmem-state.go
- pkg/pmem-state/pmem-state_test.go
- pkg/registryserver/registryserver.go
Address log-related issues listed under #497
Started with that:
Do not use Infof() logger if there are no formatted content.
Let's add more under same PR here.
Resolves  #497
> Logs cleanup, document logs use in DEVELOPMENT

- Jenkinsfile
Recently added exception handler caused continue-on-error.
> Jenkinsfile: Add "throw" statement to break pipeline on error

- pkg/pmem-grpc/grpc.go
Block more SHA1 ciphersuites, SHA1 is deprecated hence limit the usage.
> pmem-csi-driver: drop deprecated SHA1 based ciphers

- test/setup-ca-kubernetes.sh
- test/setup-ca.sh
We still had (and need) documentation for creating the Kubernetes secrets with `setup-ca-kubernetes.sh`. The removal of that script in https://github.com/intel/pmem-csi/pull/535 broke that.
This PR re-introduces the script in a version which uses `setup-ca.sh` and cleans up the output of that helper script such that normal execution just prints:
```
$ test/setup-ca-kubernetes.sh
secret/pmem-csi-registry-secrets configured
secret/pmem-csi-node-secrets configured
```
> CA secrets

- Dockerfile
The workaround was needed probably because symlink changes were not
recorded properly by Docker. When updating Clear Linux from 32480 to
version 32550 that workaround no longer was enough because
/usr/lib64/ld-linux-x86-64.so.2 itself become broken, making it
impossible to run any non-static command.
The right fix is to reconfigure Docker and overlay2 so that it uses
"Native Overlay Diff: true":
$ docker info
...
Storage Driver: overlay2
Backing Filesystem: <unknown>
Supports d_type: true
Native Overlay Diff: true
This can be done by using a kernel with CONFIG_OVERLAY_FS_REDIRECT_DIR
disabled or with a module parameter:
sudo modprobe -r overlay && sudo modprobe overlay redirect_dir=off
sudo systemctl restart docker
> Dockerfile: remove ldconfig workaround

- deploy/kubernetes-1.14/direct/pmem-csi.yaml
- deploy/kubernetes-1.14/direct/testing/pmem-csi.yaml
- deploy/kubernetes-1.14/lvm/pmem-csi.yaml
- deploy/kubernetes-1.14/lvm/testing/pmem-csi.yaml
- deploy/kubernetes-1.14/pmem-csi-direct-testing.yaml
- deploy/kubernetes-1.14/pmem-csi-direct.yaml
- deploy/kubernetes-1.14/pmem-csi-lvm-testing.yaml
- deploy/kubernetes-1.14/pmem-csi-lvm.yaml
- deploy/kubernetes-1.16/direct/pmem-csi.yaml
- deploy/kubernetes-1.16/direct/testing/pmem-csi.yaml
- deploy/kubernetes-1.16/lvm/pmem-csi.yaml
- deploy/kubernetes-1.16/lvm/testing/pmem-csi.yaml
- deploy/kubernetes-1.16/pmem-csi-direct-testing.yaml
- deploy/kubernetes-1.16/pmem-csi-direct.yaml
- deploy/kubernetes-1.16/pmem-csi-lvm-testing.yaml
- deploy/kubernetes-1.16/pmem-csi-lvm.yaml
- deploy/kustomize/driver/pmem-csi.yaml
- deploy/kustomize/testing/controller-socat-patch.yaml
- deploy/kustomize/testing/socat.yaml
- pkg/pmem-device-manager/pmd-manager_test.go
- pkg/pmem-grpc/grpc.go
- test/e2e/e2e_test.go
- test/e2e/pod/exec.go
- test/e2e/tls/nmap-ssl-enum-ciphers.patch
- test/e2e/tls/tls.go
The recent tightening of TLS ciphers came without automated testing and turned out to be surprisingly hard to test manually due to bugs in nmap.
This PR simplifies the deployment a bit and then adds full port scanning (not just currently known ports!) and checking of the TLS settings.
> check TLS settings

- README.md
- deploy/kubernetes-1.14/webhook
- deploy/kubernetes-1.15/webhook
- deploy/kustomize/webhook-1.14/kustomization.yaml
- deploy/kustomize/webhook-1.14/webhook.yaml
- deploy/kustomize/webhook/kustomization.yaml
- test/setup-deployment.sh
PR #530 broke deployment on 1.14 and 1.15 because it made all
components of a deployment mandatory but didn't add the "webhook"
link.
> deploy: fix 1.14 and 1.15, webhook was missing

- Jenkinsfile
Docker registry is used via hard-coded uuid value that is specific to
CI jenkins system, thus limiting Jenkinsfile to be functional
in this Jenkins system only where this UUID is defined.
We can make Jenkinsfile more generic by using a variable.
This variable needs to be provided by Jenkins instance.
> Small Jenkinsfile improvements

- Jenkinsfile
- test/start-stop.make
After removing the "reuse cluster" logic in
https://github.com/intel/pmem-csi/pull/548, the same cluster was used
throughout all steps, so instead of testing on the desired OS, the
tests just ran again on the initial one.
A potentially running cluster is intentionally torn down before
testing because that way we can avoid the tear down after the last
step. We don't need to do it then because the whole VM will go down.
> test: always test with a fresh cluster

- test/e2e/storage/sanity.go
The volume list by ndctl order may change. Use simplified approach
that does not pretty-print for human reader, but detects the changes
(what we really need here) and makes it ireport-order-independent via sort.
Resolves: #577
> e2e GetHostVolumes: Add sort of ndctl entries, simplify.

- operator/README.md
- pkg/pmem-csi-operator/controller/deployment/controller_driver.go
- pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go
Spreading object creation across phases is unnecessarily complex and would have to be changed anyway when introducing the "is driver running" check.
While working on this I noticed that controller test errors were attributed to the helper functions instead of the actual call site where the assertion was made, so I changed that, too.
> operator: simplify object creation

- pkg/registryserver/registryserver_test.go
Yet another error text appeared in CI testing ("rpc error: code =
Unavailable desc = write unix @->pmem-registry.sock: write: broken
pipe").
Instead of checking for specific error texts, all "rpc error: code =
Unavailable" errors are now accepted.
> test: relax TLS error check even further

- pkg/pmem-csi-operator/main.go
- test/e2e/deploy/deploy.go
- test/e2e/operator/deployment_api.go
Deleting CRD deletes all active resources which result in restarting operator pod deletes the driver. So we only delete CRD if no active deployments found.
FIXES: #579
> operator: do not delete CRD if any deployments are in active

- pkg/pmem-csi-operator/controller/deployment/deployment_controller.go
- test/e2e/deploy/deploy.go
The operator shouldn't create sub-objects for a CR that is already in the process of being deleted. That and the higher timeout should address the problem in https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/job/pmem-csi/view/change-requests/job/PR-605/1/testReport/junit/fedora-1_16.operator/API/deployment_with_defaults/
```
Unexpected error:
<*errors.errorString | 0xc00109eee0>: {
s: "timed out while trying to delete the operator-lvm-production PMEM-CSI deployment",
}
timed out while trying to delete the operator-lvm-production PMEM-CSI deployment
occurred
...
> enhance RemoveObject, fix operator handling of deleted CRs

- test/test-config.sh
This isn't relevant for the CI, but developers running
"TEST_DISTRO=fedora make start" probably will want the latest
supported Kubernetes.
> test: use Kubernetes 1.18 by default

- pkg/pmem-csi-driver/nodeserver.go
- pkg/pmem-device-manager/pmd-ndctl.go
- test/e2e/deploy/deploy.go
- test/setup-deployment.sh
- test/setup-fedora-govm.sh
- test/start-kubernetes.sh
Looking at logs shows few possibilities to reduce redundant or not relevant logs.
While changing /sys detection logging, I discovered this function may return OK in some edge cases where search for mount point or mount option does not match, which is not what we want, so there is one commit improving that part.
> Reduce logs, cover edge cases in /sys mount check

- .dockerignore
- Dockerfile
- deploy/common/pmem-app-cache.yaml
- deploy/common/pmem-app-ephemeral.yaml
- deploy/common/pmem-app-late-binding.yaml
- deploy/common/pmem-app.yaml
Dockerfile: Add pmem-dax-check and fio bundle in -test image.
Changed image:busybox to pmem-csi-driver-test in deployment examples.
Resolves: #620
> Add test utils in testing image, change busybox to testing image in examples

- Makefile
When building the docsite, we want to know when new warnings show up,
like malformed file references or new files that aren't included in
the docsite.
Fixes: #638
> docs: print all warnings, abort if any were found

- conf.json
- docs/DEVELOPMENT.md
- docs/install.md
The Kata Containers PR (https://github.com/intel/pmem-csi/pull/500)
and tightening docsite
validation (https://github.com/intel/pmem-csi/pull/640) were merged
independently without retesting, which broke "devel" because some of
the changes for Kata Containers caused warnings which are now errors.
> doc: resolve docsite warnings for Kata Containers PR

- Jenkinsfile
- Makefile
- conf.py
- deploy/kustomize/memcached/ephemeral/kustomization.yaml
- deploy/kustomize/memcached/ephemeral/memcached-ephemeral.yaml
- deploy/kustomize/memcached/persistent/kustomization.yaml
- deploy/kustomize/memcached/persistent/memcached-persistent.yaml
- examples/memcached.md
- examples/readme.rst
Memcached is a good example because images are readily available, PMEM
can be used with and without persistency, and plain yaml files are
sufficient for deployment.
> examples: memcached with and without warm restart

- Makefile
- conf.json
- conf.py
- docs/DEVELOPMENT.md
- docs/autotest.md
- docs/install.md
- docs/js/copybutton.js
- docs/requirements.txt
- examples/gce.md
- examples/memcached.md
- examples/redis-operator.md
- make.bat
- tox.ini
Addresses conversation in #633 
1. Enable copy button in code blocks.
2. Add "ShellSession" to lexer that extends "console" lexer.
**Examples pulled from examples/gce.md** 
Copy button behavior as defined by this PR:
1. "$ " defined as global prompt.
2. If prompt appears at the beginning of any line in any code block, only lines with the prompt will be copied by the button. Here only "kubectl get pv" will be copied (line 272 in gce.md).
````
```console
$ kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                       STORAGECLASS       REASON   AGE
pvc-0c2ebc68-cd77-4c08-9fbb-f8a5d33440b9   4Gi        RWO            Delete           Bound    default/pmem-csi-pvc-ext4   pmem-csi-sc-ext4            2m52s …
> Update to docsite

- docs/autotest.md
- test/test-config.sh
We recently stopped testing Clear Linux in the CI, so it also
shouldn't be the default for a manual "make start".
Fixes: #672
> test: Fedora as default for TEST_DISTRO, doc update

- docs/install.md
Appending _work/bin to the $PATH can cause errors if there are
incompatible installation of the same tool in $PATH, e.g.
having cfssl older version installed can cause this failure in
certificate creation:
```
cfssl -loglevel=3 gencert -ca=ca.pem -ca-key=ca-key.pem -
flag provided but not defined: -loglevel
```
Prepending $PATH with a path to locally installed tools should
make them running even if there are other installations of the
same tools available.
> docs: make sure installed tools have a usage priority

- test/setup-clear-govm.sh
- test/setup-fedora-govm.sh
- test/setup-kubernetes.sh
- test/test-config.sh
Using containerd directly should be simpler and allows us to test Kata
Containers also with Fedora.
Fixes: #671
> Fedora containerd

- pkg/pmem-csi-driver/pmem-csi-driver.go
Used klog.WarningF and klog.Errorf instead of klog.V(N).Info to output
"Failed..." messages.
This should ensure that the "Failed" messages will not be skipped
from the output.
> pmem-csi-driver: use appropriate klog APIs for "Failed" messages

- pkg/grpc-server/server.go
- pkg/pmem-csi-driver/controllerserver-master.go
- pkg/pmem-csi-driver/controllerserver-node.go
- pkg/pmem-csi-driver/identityserver.go
- pkg/pmem-csi-driver/main.go
- pkg/pmem-csi-driver/nodeserver.go
- pkg/pmem-csi-driver/pmem-csi-driver.go
- pkg/pmem-csi-driver/pmem-csi-driver_test.go
This is a first step in generalizing current APIs.
Renamed variables and fields of pkg/pmem-csi-driver/ and some of its depdendencies.
Avoided renaming files to keep git history cleaner.
> Rename pmem -> csi (variables and fields)

- README.md
Using the URL which redirects to the latest release has the advantage
that if we forget to update the link, users will still find the latest
release.
Also includes some slight wording tweaks.
> docs: document 0.7.0 release

- README.md
The advantage of the .svg over .png is that the .svg version includes
a play arrow, so it is more obvious that one has to click the image.
> docs: use asciinema .svg

- docs/install.md
"Raw block volumes" and "Enable scheduler extensions" were nested
under "Ephemeral inline volumes".
> docs: fix install subsections

- docs/install.md
- pkg/apis/pmemcsi/v1alpha1/deployment_types.go
- pkg/deployments/load.go
- pkg/pmem-csi-operator/controller/deployment/controller_driver.go
- pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go
- pkg/pmem-csi-operator/controller/deployment/testcases/testcases.go
Not all clusters use /var/lib/kubelet as state directory for kubelet
(kubernetes-csi/csi-driver-host-path#71). There is no way for the operator
to auto-detect this path. Hence, added a new field to deployment spec that
could be used to provide the kubelet path to driver deployment.
FIXES: #668
> operator: API to configure kubelet directory path

- deploy/bindata_generated.go
- deploy/kustomize/operator/operator.yaml
- deploy/operator/pmem-csi-operator.yaml
On OpenShift clusters operator fails to create deployment sub-resources
with below error:
I0819 15:01:16.792903       1 deployment_controller.go:255] Creating 'default/pmem-deployment-registry-secrets' of type '*v1.Secret'
I0819 15:01:16.803108       1 deployment_controller.go:169] Requeue: true, error: secrets "pmem-deployment-registry-secrets" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil># Please enter the commit message for your changes. Lines starting
This change fixes the wrongly placed 'deployments/fainalizers'.
> operator/deploy: Fix for OpenShift

- docs/install.md
- go.mod
- pkg/apis/pmemcsi/v1alpha1/deployment_types.go
- pkg/pmem-csi-operator/controller/controller.go
- pkg/pmem-csi-operator/controller/deployment/controller_driver.go
- pkg/pmem-csi-operator/controller/deployment/deployment_controller.go
- pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go
- pkg/pmem-csi-operator/main.go
Currently, we are generating 'NewDeployment', 'Running' and 'Failed'
events on a deployment. Event.Message will hold a detailed failure
reason.
We might consider generating more detailed events as the deployment
progress, which we can implement based on this change.
FIXES #542
> Operator: emitting events on deployment

- pkg/pmem-device-manager/pmd-lvm.go
Division as integer and then multiply, sheds off some value
from canUse size, and later when we align down by Align size,
we will lose whole alignment block because of that.
This creates issue where 1st run leaves one realAlign-sized block
unallocated, but 2nd start on same node will find it and create
a new relatively small namespace.
> Dev-manager canUse calc: fix operator order

- Dockerfile
- README.md
golang-lru is MPL-2.0 and needs to be distributed.
> build: document and distribute copyleft code

- pkg/pmem-csi-operator/controller/deployment/controller_driver.go
Set deployment CR defaults before finding the changes. Otherwise we get
wrong change list.
> operator: Initialize deployment CR defaults at right place

- deploy/kustomize/operator/operator.yaml
- pkg/apis/pmemcsi/v1alpha1/deployment_types.go
- pkg/pmem-csi-operator/controller/deployment/controller_driver.go
- pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go
- test/e2e/operator/validate/validate.go
Different operator releases might result in obsolete sub-resources that were created for a deployment.  Operator shall detect these obsolete objects if any and delete them in the reconcile loop.
There is no direct API to detect all the objects owned by an object. So, we solve this by annotating the Deployment CR with the list of object types & names, and the version of the operator that reconciled. On operator upgrade/degrade we check if any pre-deployed objects are still valid.
FIXES #595
> pmem-csi-operator: delete obsolete objects of a deployment

- test/setup-fedora-govm.sh
- test/test-config.sh
Kubernetes 1.19.1 may have some relevant bug fixes. More importantly,
EndpointSlices are now also disabled for it by disabling the feature
that uses them in kube-proxy. That part was missing before, causing
kube-proxy to fail.
Perhaps this will increase stability of Kubernetes 1.19 testing. There
have been random failures recently during sanity testing where
connecting to the node port failed.
> test: Kubernetes 1.19.1 without EndpointSlices

- Jenkinsfile
4 hours are no longer enough for current "devel" branch testing. 6
hours will be enough for the upcoming version skew testing.
> test: bump CI job timeout to 6 hours

- deploy/kustomize/operator/operator.yaml
- pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go
- test/e2e/operator/deployment_api.go
- test/e2e/operator/driver.go
- test/e2e/operator/validate/validate.go
This is the regression test for PR #743.
Also includes one drive-by comment fix.
> operator testing

- docs/design.md
- pkg/pmem-csi-operator/controller/deployment/controller_driver.go
- pkg/pmem-csi-operator/pmem-tls/tls.go
- pkg/pmem-csi-operator/pmem-tls/tls_test.go
- pkg/pmem-grpc/grpc.go
- test/setup-ca.sh
- test/test.make
Using of certificate CommonName is deprecated in Go-1.15.
Made changes to the self-signed certificate generation and client certificate
verification code so that now they work on DNSNames instead of CommonName.
Whereas the certificate generation using `cfssl` tools in`setup-ca.sh`
script already setting the hostname(s) which is good enough for us.
`cfssl` treats as an error if no Subject set, so keep setting the CN.
Also updated to the latest cfssl release - v1.4.1
> go-1.15-2 + certificate generation

- README.md
Declaring the entire project as "alpha" is not correct anymore,
several features are considered stable and ready for
production. However, some may still be experimental. We need to
document this in more detail.
Fixes: #631
> README.md: document feature status with more granularity

- Dockerfile
Our "apt-get upgrade" + "apt-get install" layer is something where we
pull binaries from Debian and publish on Docker Hub, i.e. we
re-distribute binaries under their respective licenses. To fulfill the
obligation of making the source code available we download the source
code from Debian and include it in the image.
This is easier than maintaining a separate download location for the
source code and the extra size is small enough (10MB for the
production image, 100MB for the test image).
> Dockerfile: include copyleft source code of extra packages

- conf.json
- conf.py
- docs/requirements.txt
I've moved the code for sphinx-md to pypi.org to make it easier to consume updates for multiple projects now relying it. This also means less code to maintain in the conf.py.
Signed-off-by: Kevin Putnam <kevin.putnam@intel.com>
> Documentation: sphinx-md is now available from pypi

- Makefile
- deploy/common/pmem-app-generic-ephemeral.yaml
- hack/set-version.sh
- operator/operator.make
- test/e2e/deploy/deploy.go
Trying to release v0.8.0 revealed a few issues around versioning. With these changes, doing a v0.8.0 should be smoother.
> release preparations

- docs/DEVELOPMENT.md
The anchor in the URL was spelled incorrectly and "cp -r" must copy
the content of the directory, not the directory.
> docs: minor fixes for "release PMEM-CSI operator"

- Dockerfile
By moving the command which pulls Debian package sources before the
settings for the PMEM-CSI binaries, test and production images can
share the same cached result of that command.
Switching between different PMEM-CSI source code also no longer causes
a re-download.
> build: better caching of Debian package sources

- docs/install.md
- examples/memcached.md
`console` copies just the commands and not their output, but doesn't
handle EOF. `ShellSession` copies everything, including EOF. We need
to be careful about using these correctly, otherwise the copy button
doesn't work as intended.
One limitation is that we cannot mix commands with output and commands
with EOF in the same code block.
Fixes: #773
> docs: fix shell session quoting

- Dockerfile
- hack/python3-fake-debian-package
Python3 is needed by xfsprogs only for a single script that we don't
need at runtime. Therefore we can avoid installing this rather large
package and its dependency by providing "python3:any" with an empty
stub package.
> build: avoid installing Python3

- Dockerfile
- hack/python3-fake-debian-package
Python3 is needed by xfsprogs only for a single script that we don't
need at runtime. Therefore we can avoid installing this rather large
package and its dependency by providing "python3:any" with an empty
stub package.
(cherry picked from commit 26c4eb559865ca7a4b1663003a9737ba9b7995ca)
> 0.8: build: avoid installing Python3

- docs/install.md
Node registrar image field name is mismatched in documentation.
> doc: Fix typo in operator CRD description

- docs/DEVELOPMENT.md
- hack/merge-release.sh
I got annoyed with `git describe` output that refers to the v0.5.0 tag. This script fixes that by making the other release tags reachable from the "devel" branch.
The PR contains both the changes and such a fabricated merge commit.
> fake merge of release branch

- pkg/apis/pmemcsi/v1alpha1/deployment_types_test.go
With the recent change of moving to V1 CRD API also needs changes to
appropriate test.
> operator: Fix test failure with recent CRD version change

- deploy/kustomize/olm-catalog/bases/pmem-csi-operator.clusterserviceversion.yaml
- operator/operator.make
- pkg/apis/pmemcsi/v1alpha1/deployment_types_test.go
- test/start-operator.sh
Various fixes to generated CVS:
- add missing mandatory fields.
- set date of CVS to the current date.
- make 'AllNamespaces' install mode to false.
- fix an issue in version patching.
> Olm catalog: Various fixes

- Jenkinsfile
After move to use Debian as base image, we do not have 'ps'
installed so that part always failed. As jobs seem to run
without trouble, let's remove this part.
Resolves: #791
> Jenkinsfile: do not run ps and kill based on that set

- deploy/crd/pmem-csi.intel.com_deployments.yaml
- operator/operator.make
An invalid deploy/crd/pmem-csi.intel.com_deployments.yaml file was
checked in as part of commit b4d17343a8b97785f0aab17b4cd25a9561fb4312
and we didn't noticed until after merging the PR because we didn't
have a test for it and the broken file only caused problems later when
trying to update the master branch (working directory not clean).
Adding the test also showed that "operator-generate-bundle" was
broken (used version in the wrong format).
Fixes: https://github.com/intel/pmem-csi/issues/798
> operator: fix and test code generation

- pkg/errors/errors.go
- pkg/ndctl/ndctl.go
- pkg/ndctl/region.go
- pkg/pmem-csi-driver/controllerserver-master.go
- pkg/pmem-csi-driver/controllerserver-node.go
- pkg/pmem-csi-driver/nodeserver.go
- pkg/pmem-device-manager/pmd-lvm.go
- pkg/pmem-device-manager/pmd-manager.go
- pkg/pmem-device-manager/pmd-manager_test.go
- pkg/pmem-device-manager/pmd-ndctl.go
- pkg/pmem-device-manager/pmd-util.go
- test/e2e/storage/sanity.go
If CreateVolume fails for a volume with late binding, the Kubernetes
scheduler is supposed to be told that it needs to reschedule the
pod. This didn't work with PMEM-CSI because it returned an "internal"
error code instead of the "resource exhausted" one that the
external-provisioner knows about.
Instead of having different well-defined errors at different levels of
the PMEM-CSI software stack, a common error package is used. These
errors get wrapped when it is useful to add more information. We still
add the gRPC error code, though. That could be avoided by making
the internal errors based on gRPC but it is uncertain whether we want
to go that far.
> pmem-csi-driver: fix rescheduling after CreateVolume failure

- operator/operator.make
- Don't invoke "docker" while parsing the Makefile.
It slows down unrelated build targets and causes
errors when Docker is not found.
Fixes: https://github.com/intel/pmem-csi/issues/804
- Consistently suppress command invocation output
during "operator-generate-catalog".
- Remove the container in which operator-courier
runs after use, otherwise it is kept around
by Docker and blocks removal of the image.
- Check the return code of running operator-courier
to detect errors that didn't cause a WARNING
to be printed (for example, problems with
setting up the container or worse, an actual
ERROR from operator-courier).
> build: multiple fixes for operator-courier integration

- test/e2e/storage/csi_volumes.go
We no longer test on the platform (Clear Linux) which had problems
passing the test, so now it may be possible to use it again.
Another issue was that the increased usage of the PMEM data files on the build host caused it to run out of filesystem space. This was fixed by increasing the VM's disk.
Fixes: https://github.com/intel/pmem-csi/issues/685
> test: enable stress test again

- docs/install.md
Sphinx, in contrast to GitHub, doesn't handle tables where some rows
have | at the start and end and some don't.
Fixes: https://github.com/intel/pmem-csi/issues/803
> docs: fix metric query example tables

- docs/install.md
An admin reading the introduction needs to know about this, otherwise
they'll get the rather obscure "PMEM-CSI not found" issue.
Fixes: #707
> docs: mention kubelet data path pitfall

- deploy/common/pmem-app-block-volume.yaml
- deploy/common/pmem-csi.intel.com_v1alpha1_deployment_cr.yaml
- docs/autotest.md
- docs/install.md
- test/e2e/deploy/deploy.go
- test/e2e/operator/deployment_api.go
- test/setup-deployment.sh
- test/start-kubernetes.sh
- test/test-config.sh
By using NFD we ensure that the integration with it works as intended.
TODO:
Fixes: issue #747
> use NFD for node labelling

- README.md
- test/e2e/versionskew/versionskew.go
0.7.x was declared obsolete by the end of October when releasing
0.8.0. We no longer need to test or support it.
> release-0.8: disable 0.7.x

- test/e2e/storage/csi_volumes.go
This reverts commit b9079bedf12ee888b2fae77a90303ce4e244ca57.
The test works and triggers volume leaks, which then fails our test
and branch build jobs (https://github.com/intel/pmem-csi/issues/823).
We have to disable it until we have a fix.
> Revert "test: enable stress test again"

- deploy/crd/pmem-csi.intel.com_deployments.yaml
- deploy/crd/pmem-csi.intel.com_deployments_webhook.yaml
- docs/install.md
- pkg/apis/pmemcsi/v1alpha1/deployment_conversion.go
- pkg/apis/pmemcsi/v1alpha1/deployment_types.go
- pkg/apis/pmemcsi/v1beta1/deployment_types.go
- test/e2e/deploy/operator.go
- test/e2e/operator/deployment_api.go
This covers validation, defaulting and conversion.
> various operator fixes

- pkg/pmem-csi-driver/nodeserver.go
- test/e2e/operator/deployment_api.go
Node server checks in which device mode the volume was created while
fetching the device details and uses the same device manger to fetch the
details. This allows the volume(s) are accessible even after the driver
switching the device mode.
FIXES #632
> pmem-csi-driver: stage/publish volumes created in different mode

- docs/design.md
Several links to the section correctly use "#kata-containers-support"
as anchor, but the section itself had the wrong title, leading
to broken links.
> docs: fix "Kata Containers" section name in design doc

- pkg/pmem-csi-operator/controller/deployment/controller_driver.go
- pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go
After operator pod restart due to unexpected shutdown it should able to
reconcile the deployment(s) that was incomplete in previous run. To test
this we inject panic in test client for mimicking the unexpected
shutdown and re-instantiate the reconciler object that mimics operator
restart.
FIXES #612
> operator: a test to verify unexpected operator shutdown

- test/setup-kubernetes.sh
Seems like weave-net CNI fails to start some time as observer in
https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/blue/rest/organizations/jenkins/pipelines/pmem-csi/branches/devel/runs/302/nodes/88/steps/151/log/?start=0:
```
[2021-01-21T08:42:56.118Z] kube-system              kube-scheduler-pmem-csi-govm-master            1/1     Running             0          23s   172.17.0.4   pmem-csi-govm-master    <none>           <none>
[2021-01-21T08:42:56.119Z] kube-system              weave-net-m6pb4                                1/2     CrashLoopBackOff    1          21s   172.17.0.4   pmem-csi-govm-master    <none>           <none>
```
And the Calico CNI plugin is used by kubeadm for its E2E testing, so
this is more suitable option than weave-net for our test cluster.
> test-cluster: Switch to calico CNI on fedora

- pkg/pmem-csi-driver/nodeserver.go
Concurrent access of the map elements without locking resulted in
panic:
```
[2021-01-21T18:14:33.903Z] pmem-csi-intel-com-node-86n58/pmem-driver@pmem..ker1: fatal error: concurrent map read and map write
[2021-01-21T18:14:33.903Z] pmem-csi-intel-com-node-86n58/pmem-driver@pmem..ker1:
[2021-01-21T18:14:33.903Z] pmem-csi-intel-com-node-86n58/pmem-driver@pmem..ker1: goroutine 339 [running]:
[2021-01-21T18:14:33.903Z] pmem-csi-intel-com-node-86n58/pmem-driver@pmem..ker1: runtime.throw(0x19dbd0d, 0x21)
[2021-01-21T18:14:33.903Z] pmem-csi-intel-com-node-86n58/pmem-driver@pmem..ker1: 	/go/src/runtime/panic.go:1116 +0x72 fp=0xc0002a7408 sp=0xc0002a73d8 pc=0x43d432
[2021-01-21T18:14:33.903Z] pmem-csi-intel-com-node-86n58/pmem-driver@pmem..ker1: runtime.mapaccess2_faststr(0x1796d00, 0xc0001d5e60, …
```
> pmem-csi-driver: fix race condition

- deploy/bindata_generated.go
- deploy/kustomize/operator/operator.yaml
- deploy/operator/pmem-csi-operator.yaml
- test/start-operator.sh
- test/test-config.sh
Operator running in e2e tests was not showing any logs, and the reason is
that there is no log verbosity level set for the operator deployment.
The default level is 0 which suppress all informative logs.
The generated operator manifest is set to log level 3, and the test
script updates it with the TEST_OPERATOR_LOGLEVEL environment value,
which defaults to 5.
> operator: set operator's log verbosity level

- test/e2e/operator/deployment_api.go
Use of dummy image name only creates many real requests to docker repo
server. The intent here is to avoid connecting real server if
we know we will fail, and also hopefully we can fail quicker.
> test/e2e/operator: use localhost with closed port for dummy image

- Jenkinsfile
- test/e2e/deploy/deploy.go
Skew testing broke when introducing 1.20 because older PMEM-CSI
releases didn't have a deployment directory for it. A symlink to 1.19
works because that deployment is okay also for 1.20.
> test: fix version skew testing on Kubernetes 1.20

- test/e2e/operator/deployment_api.go
- test/e2e/pod/logs.go
"validateDriver" does not verify that the pods are created, so it was
possible to attempt log retrieval before the pod had actually
started. Retrying for all errors fixes that.
Fixes: https://github.com/intel/pmem-csi/issues/840
> test: retry when log output is not available yet

- test/e2e/pod/logs.go
Because of == instead of != no retries were attempted.
> test: fix retry after error

- test/test.make
- skip driver late-binding stress tests in direct mode - supposed to save ~40m
- limit running package manager and imagefile unit tests part of E2E tests - supposed to save ~10m
> Adjustments to E2E tests to decrease CI test run time

- test/setup-ca.sh
Calling this script fails when no CA directroy/certificates are not found:
```
./test/setup-ca-kubernetes.sh
realpath: /home/tomz/container/openshift/pmem-csi/pmem-csi/_work/pmem-ca/ca.pem: No such file or directory
realpath: /home/tomz/container/openshift/pmem-csi/pmem-csi/_work/pmem-ca/ca-key.pem: No such file or directory
Generating Certificate for 'pmem-registry'(NS=pmem-csi) ...
```
> setup-ca.sh: create missing CA certificates

- deploy/kustomize/olm-catalog/bases/pmem-csi-operator.clusterserviceversion.yaml
CSV:
- add missing CRD 'displayName','description' fields.
- Deployment -> PmemCSIDeployment naming changes
- mention NFD usage
example CR:
- set `storage: pmem` as the default node selector.
> Fixes to operator CSV/catalog and example CR

- docs/install.md
- pkg/pmem-device-manager/pmd-util.go
shred default behavior is to write random data, but getting random data is slower than writing zeroes. In my small test with 8G file, I saw write with zeroes being almost twice faster than write with random. shred has option to add zero-fill at the end, but with setting number of random writes to zero, there will be only zero-write pass. 
I want to see how this affects overall test duration.
Also, we may discuss is fill with zeroes actually enough for real operation of the plugin, instead of even more secure fill-with-random style.
> Overwrite with zero instead of random when shredding

- pkg/deployments/load.go
- pkg/deployments/load_test.go
- pkg/pmem-csi-operator/controller/deployment/controller_driver.go
- pkg/pmem-csi-operator/controller/deployment/deployment_controller.go
- pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go
- test/e2e/operator/deployment_api.go
- test/e2e/operator/validate/validate.go
When handling change or delete events for sub-objects, in particular
MutatingWebhookConfig, a pmemCSIDeployment was created and used
without loading the TLS secret, resulting in a MutatingWebhookConfig
which had an empty CA bundle. That in turn led to:
failed calling webhook "pod-hook.pmem-csi.intel.com": Post "https://second-pmem-csi-intel-com-scheduler.default.svc:443/pod/mutate?timeout=30s": x509: certificate signed by unknown authority
> operator: load TLS CA bundle also when handling sub-object changes

- test/setup-deployment.sh
The webhook was kept as mandatory for testing when relaxing the
default, with the rationale being that we want to know if it starts
failing. But we do get test flakes because of that. Normally, pod
creation would get retried, it's just that many E2E tests don't do
that.
It's better to let the tests run and cover testing of the webhook
through WaitForPMEMDriver which explicitly creates a pod and verifies
that the webhook was invoked.
> test: allow webhook failures during testing

- deploy/kustomize/olm-catalog/bases/pmem-csi-operator.clusterserviceversion.yaml
The documentation sections like prerequisite and driver deployment
instructions de-duplicates with original PMEM-CSI readme documentation.
Instead we can point to PMEM-CSI documentation.
FIXES #891
> olm-catalog: Drop redundant sections in documentation

- Jenkinsfile
- test/setup-fedora-govm.sh
Kubernetes v1.20.2 has a [regression](https://github.com/kubernetes/kubernetes/issues/97288), which resulted in the slowness of CI builds. This got addressed in later releases. 
By moving to 1.20.4 we could re-enable 1.20 testing.
FIXES: #88
> Re-enable k8s 1.20 testing

- Jenkinsfile
- test/setup-fedora-govm.sh
Minor versions have advanced significantly, lets stick to latest.
The cmd (as comment) for showing latest versions needed update.
also:
Fixes #911
> Testing: step up installed k8s package versions on testers.

- Jenkinsfile
Sometimes, junit step does not find reports and this
causes break of execution and some artifacts may get lost.
Let's archive artifacts before junit step.
> Jenkinsfile: archive artifacts before junit step

- docs/design.md
- docs/install.md
The comment about `allowedTopologies` was incorrect and referred to an
experiment that didn't work out. What we have to use instead are
volume binding modes and scheduler extensions.
> docs: clarify volume binding modes

- deploy/bindata_generated.go
- deploy/kustomize/operator/operator.yaml
- deploy/operator/pmem-csi-operator.yaml
- test/start-operator.sh
It's set such that it replicates the semantic of the simpler -v
parameter and and then just causes more overhead in klog. In addition,
setting -v was broken because
's;-ve=.*;-v=*=${TEST_OPERATOR_LOGLEVEL};g' didn't match.
> deploy: remove redundant -vmodule operator parameter

- pkg/exec/exec.go
- pkg/exec/exec_test.go
Commit 40ba3555a43fa2aa8aa1f081af1f2386edda4dd8 intentionally captured
stderr in the output because earlier it was hard to understand why LVM
commands failed. However, we now learned the some error messages can
be safely ignored and not doing so broke LVM mode: when /dev/sda is
unreadable, "vgs" prints a line about it on stderr, but the output on
stdout is fine.
Now we capture both output streams separately, log both, but only
return stdout to the caller.
The TestResult call is unrelated to that fix and will be used for
additional debugging in another PR. It gets added here because it can
use the same test cases and is related.
Fixes: #925
> exec: cleanly separate stdout/stderr

- test/e2e/metrics/metrics.go
- test/e2e/pod/dial.go
With port forwarding through the API server we no longer need a
running container with socat inside it. For the metrics test it makes
no big difference, but the new code might be useful also for other
tests.
> test: retrieve metrics with port forwarding instead of socat

- deploy/common/pmem-app-cache.yaml
- deploy/common/pmem-app-ephemeral.yaml
- deploy/common/pmem-app-generic-ephemeral.yaml
- deploy/common/pmem-app-late-binding.yaml
- deploy/common/pmem-app.yaml
- deploy/common/pmem-kata-app-ephemeral.yaml
- deploy/common/pmem-kata-app.yaml
The 'pmem-csi-driver-test' container runs with 'pmem-csi' user which
does not allow to access to mounted /data volume. Change the permissions
on the /data mount by using pod security context.
FIXES #926
> deploy: set fsgroup for the pod in application example(s)

- Jenkinsfile
Recent changes have add testing and made runtime > 9h causing that periodic CI job started failing.
Also, let's unify all stages to 12h, as 14h for 1.20 was experimental during times when 1.20 started to run much longer than other versions, the condition which was later improved, thus all stages were taking similar time 8..9h (before most recent increase that is)
> Jenkinsfile: increase stage timeouts and unify to 12 hours

- pkg/pmem-csi-operator/controller/deployment/controller_driver.go
On redeploying the objects operator should not unset the defaults chosen
by the API server, otherwise it results in patch diff and leads to
unnecessary update object call. This is observed both driver
statefulset and daemonset objects.
To avoid this we have two options:
1. set only specific options instead of total refresh.
2. set also the default values
We chose option 1 while setting daemonset and statefulset specification
fields, and option 2 for setting container values.
FIXES #924
> operator: avoid unexpected object patching

- deploy/bindata_generated.go
- deploy/kustomize/operator/operator.yaml
- deploy/operator/pmem-csi-operator.yaml
- docs/install.md
- pkg/pmem-csi-operator/controller/deployment/controller_driver.go
- pkg/pmem-csi-operator/controller/deployment/deployment_controller.go
- pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go
- pkg/pmem-csi-operator/main.go
- pkg/pmem-csi-operator/metrics/metrics.go
- test/e2e/deploy/cluster.go
- test/e2e/deploy/deploy.go
- test/e2e/deploy/operator.go
- test/e2e/metrics/metrics.go
- test/e2e/operator/deployment_api.go
- test/e2e/operator/driver.go
- test/e2e/operator/validate/validate.go
- test/e2e/storage/sanity.go
- test/e2e/versionskew/versionskew.go
Added support for operator metrics, by default at port 8080, which could be configured using `--metrics-addr` command-line argument.
Changed the validation logic in e2e tests to make use of these metrics to know when a deployment CR went through the reconciliation loop and, to detect if any unexpected object updates initiated by the operator.
> Operator metrics

- go.mod
- go.sum
- test/e2e/storage/sanity.go
The resource cleanup API and implementation changed, replacing
explicit register calls with wrapping of the calls which create
resources.
The new "target path removed" test depends on another remote operation
for checking paths.
> test: update csi-test to 4.x

- operator/operator.make
- Remove scorecard tests reference from generated metadata.
- Fix CSV path while patching.
> operator: fixes to bundle generation

- deploy/kustomize/operator/operator.yaml
- deploy/operator/pmem-csi-operator.yaml
Adding this label breaks operator upgrades using OLM, as the previous
(v0.9.x) versions do not have this label that results in mismatched
label selector.
> deploy/operator: remove newly added app label from selector list

- Jenkinsfile
Due to misused shell redirection, kubelet log contained the
output from last worker only, and no cluster information.
Compress longer job logs, save kubelet logs in all cases,
means we do not need exception intercepting block any more.
> Jenkinsfile: fix logs file creation, do it always

- Jenkinsfile
This causes creating 2 workers instead of 3 in PR CI jobs.
> Jenkinsfile: check for skipping 1.18 before spawning agent

- test/e2e/metrics/metrics.go
Apparently resp.Body can be nil even when there was no error code:
```
/mnt/workspace/pmem-csi_devel/test/e2e/metrics/metrics.go:50
Test Panicked
/go/src/runtime/panic.go:212
Panic: runtime error: invalid memory address or nil pointer dereference
Full stack:
github.com/intel/pmem-csi/test/e2e/metrics.glob..func1.2.1()
/mnt/workspace/pmem-csi_devel/test/e2e/metrics/metrics.go:81
+0x7f0
```
That's the line with `ioutil.ReadAll(resp.Body)`.
An assertion failure gets caught, a panic isn't, therefore Expect()
deals with this problem.
Fixes: #971
> test: nil pointer in metrics test

- pkg/grpc-server/server.go
- pkg/pmem-csi-driver/controllerserver-node.go
- pkg/pmem-csi-driver/pmem-csi-driver.go
- pkg/pmem-grpc/grpc.go
- pkg/pmem-state/pmem-state.go
- test/e2e/storage/sanity.go
Cleans up error and log messages (first commit), then ensures that the node name is injected into all errors returned via gRPC (second commit).
Fixes: https://github.com/intel/pmem-csi/issues/966
> node errors

- docs/install.md
This was meant to be at the same level as "Install PMEM-CSI driver"
and "Creating volumes".
> docs: fix indention of "Volume parameters"

- docs/install.md
- test/e2e/deploy/deploy.go
This was missed in 3e896ef.
Fixes: https://github.com/intel/pmem-csi/issues/973
> test, docs: drop remaining use of admissionregistration.k8s.io/v1beta1

- test/e2e/metrics/metrics.go
Apparently resp (?!) can be nil even when there was no error code.
Panic: runtime error: invalid memory address or nil pointer dereference
Full stack:
github.com/intel/pmem-csi/test/e2e/metrics.glob..func1.2.1()
/mnt/workspace/pmem-csi_PR-977/test/e2e/metrics/metrics.go:81 +0x7f0
github.com/onsi/gomega.InterceptGomegaFailures(0xc0052d4ab0, 0xc0014b2660, 0x0, 0xc002627800)
/mnt/workspace/gopath/pkg/mod/github.com/onsi/gomega@v1.10.5/gomega_dsl.go:107
+0xbb
metrics.go:81 now had:
Expect(resp.Body).NotTo(BeNil(), "have response body")
Fixes: https://github.com/intel/pmem-csi/issues/971
> test: nil pointer in metrics test, II

- docs/install.md
This shouldn't have been merged in the first place (was already
addressed, PRs shouldn't add new TODOs).
This commit is also in PR #979
> docs: remove obsolete TODO

- test/pull-images.sh
After "make push" we want to be sure that a running cluster actually
uses the new images. Our default image pull policy is "IfNotPresent",
so it won't pull each time a Pod starts. We have to use some other
mechanism.
The new test/pull-images.sh does that by definining a DaemonSet that
uses both kinds of PMEM-CSI images and has image pull policy
"Always". By changing the annotation of the pods, we force a pod
restart on each node each time the script gets invoked.
> test: force image pull

- test/e2e/operator/deployment_api.go
Using the same deployment name for both update 'while running' and
'while stopped' makes it hard depending on reconcile metric count. The
'while running' test could fail when it is run after a 'while stopped'
test as it reset the counter to zero.
FIXES #988
> test/e2e: Fix operator deployment update tests.

- Dockerfile
- docs/design.md
- pkg/ndctl/fake/region.go
- pkg/ndctl/ndctl.go
- pkg/ndctl/region.go
- pkg/pmem-device-manager/pmd-lvm.go
- pkg/pmem-device-manager/pmd-ndctl.go
We may adjust requested size upwards, so lets check for available
space after that.
This PR is meant to address points in #933
> Namespace creation size-related fixes

- go.mod
- go.sum
- pkg/logger/capacity.go
- pkg/ndctl/fake/namespace.go
- pkg/ndctl/namespace.go
- pkg/ndctl/region.go
- pkg/pmem-csi-driver/controllerserver-node.go
- pkg/pmem-csi-driver/nodeserver.go
- pkg/pmem-device-manager/pmd-fake.go
- pkg/pmem-device-manager/pmd-lvm.go
- pkg/pmem-device-manager/pmd-manager.go
- pkg/pmem-device-manager/pmd-manager_test.go
- pkg/pmem-device-manager/pmd-ndctl.go
- pkg/pmem-state/pmem-state.go
- runtime-deps.csv
- test/e2e/storage/sanity.go
- test/test.make
NodeUnstageVolume did not return the correct error code anymore when the volume didn't exist. This was found while working on a new test where volumes get deleted before running the normal cleanup code.
The actual goal was to have a test for space fragmentation and checking that the maximum volume size is handled correctly. While working on that, I ended up addressing various todos.
> volume handling cleanup and fixes

- pkg/math/math.go
- pkg/ndctl/fake/region.go
- pkg/ndctl/region.go
- pkg/pmem-device-manager/pmd-lvm.go
- pkg/pmem-device-manager/pmd-ndctl.go
We must round down to the required alignment to ensure that volumes
that use a size smaller than the maximum volume size then can be
rounded up.
Fixes: https://github.com/intel/pmem-csi/issues/1002
> pmem-csi-driver: alignment fixes for GetCapacity

- test/setup-kubernetes.sh
- test/start-kubernetes.sh
The Fedora 33 kernel runs into panics during the raw conversion
test. We need to replace 33 with 34 anyway.
Testing showed that Calico had problems with the newer Fedora while
WeaveNet worked, so that is used again.
Fixes: https://github.com/intel/pmem-csi/issues/1008
> test: Fedora 34 + WeaveNet

- Dockerfile
- deploy/common/pmem-kata-app.yaml
- docs/install.md
- pkg/pmem-csi-driver/controllerserver-node.go
- pkg/pmem-csi-driver/nodeserver.go
- test/e2e/driver/driver.go
- test/e2e/storage/dax/dax.go
- test/setup-kata-containers.sh
There were multiple issues, both in the driver and in the tests. Testing with LVM now at least brings up the Pod with working DAX volume, but then deleting the Pod hangs because of https://github.com/kata-containers/kata-containers/issues/2018
TODO:
Fixes: https://github.com/intel/pmem-csi/issues/987
> Fix Kata Containers support

- Makefile
Populating the vendor dir was done before checking the Go version,
leading to a hard failure with older versions because we now depend on
"embed" from Go 1.16.
With this fix, a proper warning is shown:
```
$ make build-image
======================================================
WARNING
This projects is tested with Go v1.16.
Your current Go version is v1.13.
This may or may not be close enough.
In particular test_fmt and test_vendor
are known to be sensitive to the version of
Go.
======================================================
go mod tidy
warning: ignoring symlink /nvme/gopath/src/github.com/intel/pmem-csi/cmd/manager
github.com/intel/pmem-csi/deploy imports
embed: malformed module path "embed": missing dot in first path element
make: *** [Makefile:118: populate-vendor-dir] Error 1 …
```
> build: check Go version during "make build-image"

- pkg/pmem-csi-driver/nodeserver.go
"dax=always" gets passed verbatim to the kernel by the mount
command. Older kernels like 5.4 then fail with "wrong fs type, bad
option, bad superblock on /dev/pmem1.1, missing codepage or helper
program, or other error."
Although "-o dax" is said to be a legacy option that may get removed,
in practice the risk of that happening is low, so we can revert to
using it without any fallbacks. It's functionally the same.
> pmem-csi-driver: revert to mounting with "-o dax"

- test/e2e/e2e_test.go
Ginkgo recently changed the semantic of -ginkgo.skip so that it
accumulates skip strings instead of setting
them (https://github.com/onsi/ginkgo/pull/736/files#r669576114). In
our case that had the effect that slow tests (like version skew) were
always skipped, regardless of the -ginkgo.skip string passed to the
e2e.test binary.
> test: remove ginkgo.skip default

- test/e2e/versionskew/operator.go
- test/e2e/versionskew/versionskew.go
Since releasing 1.0.0, the "current = 1.0" version number was not high
enough anymore with the effect that the OLM upgrade test didn't
actually upgrade and after a test run removed the files under deploy
which were still needed.
> test: bump up fictional future version number for OLM upgrade test

- test/start-stop-openshift.sh
The new installer must be downloaded manually. Once it is available,
bringing up the cluster almost works as before. Another DNS entry is
needed.
> test: update to OpenShift 4.8 GA

- examples/redis-operator.md
The install section was out-dated because the referenced Clear Linux release
is (probably) no longer available. Focusing just on a local cluster also was
too restrictive. Instead we should just mention the part that really matters,
the storage class.
Besides removing old content this also gets rid of the https://clearlinux.org
URL. That site is currently down, which breaks building our docsite due to the
failed link check.
> docs: stop referencing Clear Linux

- deploy/kubernetes-1.19/direct/pmem-csi.yaml
- deploy/kubernetes-1.19/direct/testing/pmem-csi.yaml
- deploy/kubernetes-1.19/lvm/pmem-csi.yaml
- deploy/kubernetes-1.19/lvm/testing/pmem-csi.yaml
- deploy/kubernetes-1.19/pmem-csi-direct-testing.yaml
- deploy/kubernetes-1.19/pmem-csi-direct.yaml
- deploy/kubernetes-1.19/pmem-csi-lvm-testing.yaml
- deploy/kubernetes-1.19/pmem-csi-lvm.yaml
- deploy/kubernetes-1.20/direct/pmem-csi.yaml
- deploy/kubernetes-1.20/direct/testing/pmem-csi.yaml
- deploy/kubernetes-1.20/lvm/pmem-csi.yaml
- deploy/kubernetes-1.20/lvm/testing/pmem-csi.yaml
- deploy/kubernetes-1.20/pmem-csi-direct-testing.yaml
- deploy/kubernetes-1.20/pmem-csi-direct.yaml
- deploy/kubernetes-1.20/pmem-csi-lvm-testing.yaml
- deploy/kubernetes-1.20/pmem-csi-lvm.yaml
- deploy/kubernetes-1.21/direct/pmem-csi.yaml
- deploy/kubernetes-1.21/direct/testing/pmem-csi.yaml
- deploy/kubernetes-1.21/lvm/pmem-csi.yaml
- deploy/kubernetes-1.21/lvm/testing/pmem-csi.yaml
- deploy/kubernetes-1.21/pmem-csi-direct-testing.yaml
- deploy/kubernetes-1.21/pmem-csi-direct.yaml
- deploy/kubernetes-1.21/pmem-csi-lvm-testing.yaml
- deploy/kubernetes-1.21/pmem-csi-lvm.yaml
- deploy/kustomize/patches/metrics-controller.yaml
- deploy/kustomize/patches/metrics-node.yaml
- pkg/pmem-csi-driver/pmem-csi-driver.go
- pkg/pmem-csi-operator/controller/deployment/controller_driver.go
- test/e2e/metrics/metrics.go
During a long-running DeleteVolume for a 200GB volume the LVM lock is held and
the liveness probe for metrics data timed out after a minute, killing the
container, because metrics retrieval must take the LVM lock.
As operation duration is non-deterministic, the solution is to probe only
metrics data which can be served immediately when the process is up and
running. This is less precise (= doesn't really check any functionality), but
that's an inherent problem of liveness probes: they simply cannot cover the
full functionality.
Fixes: #1046
> pmem-csi: avoid false negative liveness probe

- deploy/kustomize/olm-catalog/bases/pmem-csi-operator.clusterserviceversion.yaml
https://operatorhub.io/?keyword=intel finds the "Intel Device Plugins
Operator", probably because the word appears in the title. We don't have that
for PMEM-CSI, so list the keyword explicitly.
> operator hub: explicitly list "Intel" as keyword

- docs/DEVELOPMENT.md
- pkg/pmem-csi-driver/rescheduler.go
Main reason for the PR is an observation that some tests because the controller container restarted directly after doing some useless Delete (see commit message).
Also contains some other, minor enhancements.
> avoid Delete call in controller

- pkg/pmem-csi-driver/nodeserver.go
- pkg/xfs/xfs.go
- pkg/xfs/xfs_test.go
- test/e2e/storage/dax/dax.go
On OpenShift, the xfs_io command that was used while creating XFS volumes hangs
while getting loaded (kernel or container runtime bug?). This problem can be
avoided by making the same ioctl calls as in that binary directly from
the PMEM-CSI driver.
Fixes: https://github.com/intel/pmem-csi/issues/1058
> XFS: fix creating volumes on OpenShift

- pkg/pmem-csi-driver/nodeserver.go
- pkg/xfs/xfs.go
- pkg/xfs/xfs_test.go
- test/e2e/storage/dax/dax.go
On OpenShift, the xfs_io command that was used while creating XFS volumes hangs
while getting loaded (kernel or container runtime bug?). This problem can be
avoided by making the same ioctl calls as in that binary directly from
the PMEM-CSI driver.
Fixes: https://github.com/intel/pmem-csi/issues/1058
(cherry picked from commit 4f1a2d82218c7416511060feeae442bddf7d2e1a)
> release-1.0: XFS: fix creating volumes on OpenShift

- test/test.make
make WITH_DLV=1 test_e2e can be used to run the tests interactively
under the delve debugger.
> test: support running E2E test under dlv

- Dockerfile
It is the latest supported release at this time.
> build: bump to Go 1.18.1

- docs/design.md
- docs/requirements.txt
- pkg/scheduler/README.md
The newer markdown 3.4.1 is not compatible with sphinx-markdown-tables.
The URL for the scheduler extender changed.
> fix "make vhtml"

- test/start-operator.sh
"operator-sdk run" pulls the latest version of certain images, which started to
break after an quay.io/operator-framework/opm update. Pinning to a known
version in our invocation is a workaround for that
bug (https://github.com/operator-framework/operator-registry/issues/984).
> test: workaround operator-sdk image pinning

- Dockerfile
- pkg/imagefile/imagefile.go
- pkg/ndctl/namespace.go
- pkg/ndctl/ndctl.go
- pkg/pmem-csi-driver/pmem-csi-driver.go
- pkg/pmem-csi-operator/controller/deployment/controller_driver.go
- pkg/pmem-csi-operator/controller/deployment/deployment_controller.go
- pkg/pmem-device-manager/pmd-lvm.go
- pkg/pmem-device-manager/pmd-manager.go
- pkg/pmem-device-manager/pmd-ndctl.go
- pkg/pmem-grpc/grpc.go
- pkg/version/version.go
- pkg/volumepathhandler/volume_path_handler_linux.go
- test/e2e/deploy/deploy.go
- test/e2e/operator/validate/validate.go
- test/e2e/versionskew/versionskew.go
The main practical difference is that 1.19 has enhanced support for doc
comments and enforces certain formatting conventions.
> build: update to Go 1.19

- test/start-operator.sh
"run bundle-upgrade" does not support it, breaking the version skew tests after
merging the PR.
> test: only use --index-image for "run bundle"
