- Makefile
- README.md
- cmd/pmem-csi-driver/Dockerfile
- cmd/pmem-csi-driver/main.go
- cmd/pmem-ns-init/Dockerfile
- cmd/pmem-ns-init/main.go
- cmd/pmem-vgm/Dockerfile
- cmd/pmem-vgm/main.go
- deploy/k8s/pmem-app.yaml
- deploy/k8s/pmem-csi.yaml
- deploy/k8s/pmem-pvc.yaml
- deploy/k8s/pmem-storageclass.yaml
- deploy/k8s/pmem-unified-csi.yaml
- docs/diagrams/sequence.wsd
- pkg/pmem-csi-driver/controllerserver.go
- pkg/pmem-csi-driver/nodeserver.go
- pkg/pmem-csi-driver/pmem-csi-driver.go
- pkg/pmem-csi-driver/registryserver.go
- pkg/pmem-csi-driver/server.go
- pkg/pmem-device-manager/pmd-lvm.go
- pkg/pmem-device-manager/pmd-ndctl.go
- pkg/pmem-grpc/grpc.go
- test/e2e/e2e_test.go
- test/e2e/storage/csi_volumes.go
- test/e2e/storage/sanity.go
- test/sanity/sanity_test.go
- test/test-config.sh
This reverts commit afdf657390af5f1227023e5d9f62849f1258cc24.
Additionally, all other cases of csi-pmem chaned to pmem-csi.
> Revert "Repository name change: pmem-csi -> csi-pmem"

- pkg/ndctl/namespace.go
Simplified the logic by avoiding creating new byte array while writing to pmem
block file. Also fixed memory leak.
Fixes #113
> Fix issues in namespace nullify

- pkg/ndctl/region.go
- pkg/pmem-csi-driver/controllerserver.go
- pkg/pmem-csi-driver/nodeserver.go
- pkg/pmem-device-manager/pmd-ndctl.go
In DeleteVolume, if volume was not created, log about deletion
was still emitted.
> Improve log messages

- Gopkg.lock
- Makefile
- README.md
- cmd/pmem-csi-driver/main.go
- deploy/kubernetes-1.12/pmem-csi.yaml
- deploy/kubernetes/pmem-csi.yaml
- pkg/pmem-csi-driver/controllerserver.go
- pkg/pmem-csi-driver/identityserver-default.go
- pkg/pmem-csi-driver/identityserver.go
- pkg/pmem-csi-driver/nodeserver.go
- pkg/pmem-csi-driver/pmem-csi-driver.go
- pkg/pmem-csi-driver/registryserver.go
- pkg/pmem-csi-driver/registryserver_test.go
- pkg/pmem-csi-driver/server.go
- pkg/pmem-grpc/grpc.go
- test/setup-ca-kubernetes.sh
- test/setup-ca.sh
- test/start-stop.make
- test/test.make
Implemented mutual authentication between registry server and node controller servers, this way we can ensure the secure communication between these components. Write unit tests to test this and updated the documentation.
> Mutual authentication between pmem driver components

- pkg/pmem-device-manager/pmd-ndctl.go
In Devicemode_direct (alias ndctl), the driver can operate
only if /sys is mounted in read-write mode.
It has been seen however that sometimes container gets
deployed in such a way that /sys is mounted read-only.
It makes sense to detect writable /sys at start-time
and refuse to run, instead of stumbling to that later in operation.
> pmd-ndctl.go: Add start-time check for writable /sys

- DEVELOPMENT.md
- README-qemu-notes.md
- README.md
This file explains development-related aspects,
and we move some pieces from README over there.
New material is API explanation: sockets, arguments, etc.
This resolves #179, resolves #180
> add DEVELOPMENT.md, update README

- pkg/pmem-device-manager/pmd-lvm.go
- pkg/pmem-device-manager/pmd-ndctl.go
There was failure scenario in devicemode:direct where namespace
creation succeeded but zeroing of device did not, i.e. partial
success, but returned FAIL, which caused k8s to repeat,
and as created namespace remained there, all device space
was quickly consumed. We address this by trying to clean up
on partial failure.
Fixes #168
> CreateDevice: avoid space-exhaustion loop on partial volume creation failure

- pkg/pmem-csi-driver/nodeserver.go
Dax mount option should be used while mounting a fsdax namespace. Fsdax is the
default volume namespace mode.
Volume.VolumeContext is only filled with volume parameters that were passed by
CreateVolumeRequest.Parameters, Hence default volume parameters are not filled
in VolumeContext. Code in NodeServer.StageVolume using dax mount option only in
case of valid VolumeContext, so dax option was not used if 'nsmode' is not found
in volume context.
This change fixes this, by considering the default volume parameters if no volume
context passed.
> Fix issue in passing dax mount option.

- README.md
> Fix typo at README.md file.

- README.md
> Modify pmem-CSI naming as specified internally.

- DEVELOPMENT.md
- README-qemu-notes.md
- deploy/kustomize/driver/README.md
- deploy/kustomize/testing/README.md
>  Modify pmem-CSI naming as specified internally.

- DEVELOPMENT.md
- README-qemu-notes.md
- README.md
- deploy/kustomize/driver/README.md
- deploy/kustomize/testing/README.md
PMEM-CSI is the correct name for this project.
Fixes: #251
> revert name change

- README.md
In an actual deployment scenario, in case of problems, it
makes sense to verify each step before starting next one.
Resolves #249
> README: Add check "pvc state is Bound" in deployment steps

- deploy/kubernetes-1.13/pmem-pvc.yaml
> Update url references for storage class name used at pmem-pvc.yaml

- Dockerfile
> Advance ndctl version from 64.1 to 65

- README.md
> README: add chapter describing NVDIMM pre-provisioning with ipmctl

- test/start-kubernetes.sh
When executing long-running shell scripts on the nodes, the output was
printed in large chunks infrequently. That made it impossible to
really see what's currently happening. Now each line is printed as
soon as it is produced and also gets a time stamp.
swupd prints carriage return characters as part of the download
progress reporting. This used to overwrite the prefix with the node
name. Now those characters are removed before printing. Download
progress ends up producing many lines (one for each update), but
fixing that would require further special handling, so this has to be
good enough for now:
...
09:04:35 pmem-csi-clear-govm-worker2: Downloading packs (398.85 Mb) for:
09:04:35 pmem-csi-clear-govm-worker2: - cloud-native-basic
09:04:35 pmem-csi-clear-govm-worker2: - containers-basic …
> test: better cluster setup output handling

- Dockerfile
- Jenkinsfile
- Makefile
- test/setup-clear-govm.sh
- test/start-kubernetes.sh
- test/test-config.sh
This builds on top of and replaces https://github.com/intel/pmem-CSI/pull/157.
> Enhanced Jenkins pipeline

- README.md
I think this is enough to consider #229 resolved. The other two commits are drive-by enhancements.
> admin docs

- README.md
- examples/redis-operator.md
The example has three sections:
- PMEM-CSI installation.
- Redis operator installation and Redis cluster deployment.
- Playing around with Redis operator.
> Add an example to deploy a Redis cluster using redis-operator and PMEM-CSI

- Dockerfile
- Jenkinsfile
- Makefile
- test/e2e/storage/sanity.go
- test/setup-deployment.sh
- test/start-kubernetes.sh
- test/test-config.sh
- test/test.make
Various Jenkins pipeline enhancements.
> Jenkins enhancements

- pkg/pmem-csi-driver/controllerserver-master.go
- pkg/registryserver/registryserver.go
- pkg/registryserver/registryserver_test.go
Failures happened in RegistryListener.OnNodeAdded() are supposed to send back to
appropriate node, and the node registration should fail. This allows the node
driver to make this error visible to cluster admins via driver health check.
FIXES: #320
> RegistryServer: Report back errors from OnNodeAdded

- Jenkinsfile
- Makefile
Once we have completed all tests for a new image, we put it into a staging area for additional, internal testing.
> image publishing

- Jenkinsfile
The name of the BUILD_IMAGE must be set differently depending on
whether we do a full build or pre-merge testing.
Also, pulling images in a full build isn't useful because the
CACHEBUST value will prevent using anything from the older images, so
we can skip pulling them altogether.
Finally, changeRequest() in the script didn't work as expected.
Checking the env.CHANGE_ID does.
> CI: dynamically determine image names

- Jenkinsfile
With the help of some functions we can remove the code duplication.
Closures for lazy variable evaluation didn't work, for some reason the result always was the same.
> reduce duplication in Jenkinsfile

- pkg/pmem-device-manager/pmd-ndctl.go
Recent alignment change broke size calculation,
and compensation for smaller creation was left out.
As the result, current code would create for example 2GB
namespace per 2.x GB request, because we would
align 2.x up to 3 GB, then libndctl creatng 3-1=2GB namespace.
We have to compensate for libndctl creating one alignment step smaller
namespace. Current change should handle all: check for
too small (i.e. zero), compensate for smaller creation,
and that it all works together with alignment.
> Direct mode Namespace creation: compensate for smaller result

- DEVELOPMENT.md
- Jenkinsfile
- Makefile
- README.md
- deploy/kubernetes-1.13/pmem-csi-direct-testing.yaml
- deploy/kubernetes-1.13/pmem-csi-direct.yaml
- deploy/kubernetes-1.13/pmem-csi-lvm-testing.yaml
- deploy/kubernetes-1.13/pmem-csi-lvm.yaml
- deploy/kubernetes-1.14/pmem-csi-direct-testing.yaml
- deploy/kubernetes-1.14/pmem-csi-direct.yaml
- deploy/kubernetes-1.14/pmem-csi-lvm-testing.yaml
- deploy/kubernetes-1.14/pmem-csi-lvm.yaml
- deploy/kustomize/driver/pmem-csi.yaml
- deploy/kustomize/kubernetes-1.13-direct-coverage/kustomization.yaml
- deploy/kustomize/kubernetes-1.13-lvm-coverage/kustomization.yaml
- deploy/kustomize/kubernetes-1.14-direct-coverage/kustomization.yaml
- deploy/kustomize/kubernetes-1.14-lvm-coverage/kustomization.yaml
- deploy/kustomize/patches/lvm-patch.yaml
- hack/set-version.sh
- hack/update-clear-linux-base.sh
- test/setup-deployment.sh
This outlines what we intend to do. Not all of it is currently
implemented (no master branch, CI not fully operational).
> CI: document and implement release strategy

- DEVELOPMENT.md
- README.md
> README additions: LVM/Direct mode table, supported versions

- .dockerignore
- Dockerfile
- deploy/kubernetes-1.13/pmem-csi-lvm-testing.yaml
- deploy/kubernetes-1.13/pmem-csi-lvm.yaml
- deploy/kubernetes-1.14/pmem-csi-lvm-testing.yaml
- deploy/kubernetes-1.14/pmem-csi-lvm.yaml
- deploy/kustomize/patches/lvm-patch.yaml
This better separates OS and PMEM-CSI content and adds license files.
> container layout

- hack/set-version.sh
The version there also needs to be updated, otherwise E2E testing
fails.
> set-version.sh: also update version in test-config.sh

- README.md
- examples/gce.md
It is currently possible to use PMEM on some GCE machines, but
installing Kubernetes and PMEM-CSI is only possible with modified
images and scripts.
> docs: Google Compute Engine

- test/setup-ca-kubernetes.sh
'ls' mostly returning zero, led to cleanup never being called,
causing /tmp/pmem-xxxx directories to pile up on test host.
There seems to be no reason to ever keep WORKDIR, so
we can call cleanup unconditionally.
cleanup was misspelled in INT trap setting so it was
never called on interrupted run either.
Combining last cleanup call being part of EXIT trap.
Using pushd/popd to get into and out from WORKDIR.
Do not treat WORKDIR as possibly coming from outside,
this script creates, owns and destroys it unconditionally.
> setup-ca-kubernetes.sh: make cleanup working

- pkg/pmem-csi-driver/nodeserver.go
> Revert accidental changes in v0.5.1

- test/setup-clear-govm.sh
As noted in https://github.com/clearlinux/distribution/issues/1004,
sometimes rebooting a Clear Linux machine would result in kubelet not
coming up because the boot order happened to be such that kubelet
started before the container runtime.
In current Clear Linux 30900, this could not be reproduced when
running the test/e2e/sanity node reboot tests although the conceptual
issue still exists
(https://github.com/clearlinux/distribution/issues/1004#issuecomment-520550386).
Therefore it is worthwhile to address this potential race condition by
configuring kubelet to start after the container runtime.
> test: explicitly declare kubelet -> container runtime service dependency

- pkg/pmem-csi-driver/controllerserver-master.go
- pkg/pmem-csi-driver/controllerserver-node.go
- pkg/pmem-csi-driver/nodeserver.go
Change UUID to hash on Node side as well when creating VolumeID
> Change UUID to hash on Node side as well when creating VolumeID, logs improvement

- Jenkinsfile
GIT_LOCAL_BRANCH used to be set for tag and branch builds, but now is
only set for tag builds, with the result that pushing canary images
failed when trying to use the unset GIT_LOCAL_BRANCH.
> CI: adapt usage of GIT_LOCAL_BRANCH

- Jenkinsfile
- test/setup-clear-govm.sh
- test/setup-kubernetes.sh
- test/start-kubernetes.sh
This is PR #422 plus enhanced cluster setup.
> testing on Kubernetes 1.15

- test/e2e/storage/sanity.go
Added more tests for persistent volume to cover the below cases:
- to assure volume only gets allocated on single node
- has the right topology information
- retains data across app restarts
FIXES #213
> test: more sanity tests for persistent volume

- pkg/pmem-csi-driver/controllerserver-master.go
- test/e2e/storage/sanity.go
If topology is set in GetCapacityRequest, we should return only pmem capacity
for that topology/node instead the cluster-wide capacity.
> Controller: Consider topology in GetCapacity() request

- Dockerfile
New version has just been released, lets see how this goes in our CI
> Use ndctl version 67

- DEVELOPMENT.md
- README.md
Starting block with "This" is bit fuzzy as there are multiple
preceding statements where "This" could relate to.
> README: minor correction and improvement

- pkg/pmem-csi-driver/nodeserver.go
By CSI spec, NodeUnpublish has to return NOT_FOUND if
volume does not exist, but currently we don't check it
before umounting, so we will return different status.
Resolves #403
> NodeUnpublishVolume: check for VolumeID existence first

- test/e2e/storage/csi_volumes.go
- test/e2e/storage/sanity.go
If a tester creates volumes that are not deleted properly,
we will have leftover device volumes (not CSI volumes)
after testing. Let's try to detect those using device
volume list commands.
Resolves #286
> test/e2e/storage/ : add check for leftover volumes

- test/test.make
"test_e2e" must have the same make dependencies as "run_tests" because
it embeds those.
> test: fix "make test_e2e" dependencies

- pkg/pmem-device-manager/pmd-ndctl.go
It is uncertain whether libndctl supports concurrent operations while
a context is open. To minimize the risk it is better to start each
operation with a new context.
Update: Dan Williams confirmed that "one libndctl instance expects it is the only agent manipulating the kernel state. A single instance can make any changes it wants without refreshing the context" - this implies that if there are multiple instances (like PMEM-CSI and ndctl command line), the context must be refreshed, as we do here.
> ndctl: use fresh context for each operation

- DEVELOPMENT.md
- README.md
It's worthwhile to state right at the beginning of our main landing
page (= README.md) what we currently support and how we handle tags
because users need to know that when picking something to install.
Doing a release involves certain steps. We had documentation for most
of that, but not a single simple check list.
> docs: describe latest release and how to create a new one

- Dockerfile
- Makefile
One cosmetic change and one fix.
> build improvements

- Dockerfile
- Jenkinsfile
- Makefile
- README.md
- test/start-kubernetes.sh
- test/test-config.sh
A variety of fixes from "devel". The one for VMX is critical to get release-0.6 building again on Azure.
> Release 0.6 fixes

- pkg/pmem-grpc/grpc.go
By default 3DES ciphers are enabled by 'crypto/tls' package which are vulnerable
to SWEET32 attack.  This change disables insecure ciphers from supported
ciphersuite list.  Currently blocked ciphers are 3DES and RC4.
These is no direct way offered by 'crpyto/tls' package to disable a single
cipher from tls.Config. So we do this by preparing per client connection config
using tls.Conig.GetConfigForClient. This function gets called while connection
handshaking where client sends ClientHelloInfo with the cipher suites it
supported. Where we filter out the insecure ciphers from that list and set to
newly created tls.Config.
Here is the `nmap` output run aginst node controller server:
```
$ nmap --script +ssl-enum-ciphers -p 10001 172.17.0.4
Starting Nmap 7.60 ( https://nmap.org ) at …
```
> pmem-csi-driver: disable insecure ciphers

- pkg/pmem-csi-driver/controllerserver-master.go
- pkg/pmem-csi-driver/controllerserver-node.go
> Handle hash collision

- Jenkinsfile
- test/setup-kubernetes.sh
Both get bumped up to the current latest release.
> test: update Clear Linux and Flannel

- test/setup-deployment.sh
- test/start-kubernetes.sh
- test/start-stop.make
Some minor bug fixes (wrong log output, missing removal of cluster directory) and code cleanup.
> test setup cleanup

- go.mod
- go.sum
- test/e2e/deploy/deploy.go
- test/e2e/storage/sanity.go
- test/e2e/storage/wait.go
This should reduce the amount of "failed at attempt" log messages.
Fixes: #564
> test output

- pkg/pmem-csi-driver/controllerserver-node.go
- pkg/pmem-state/pmem-state.go
- pkg/pmem-state/pmem-state_test.go
Current sm.GetAll() is error prone if the caller does not reset the dataPtr read for each element, this was visible in issue #569.
With this change GetAll() only returns all ids of the elements found, then caller has to call Get() on each record he interested in.
Fixes: #569
> pmem-csi-driver: change semantics of StateManager.GetAll()

- test/e2e/pod/exec.go
- test/e2e/tls/tls.go
Fixes output (cosmetic change) and retries nmap (real change).
> flaky TLS testing

- test/e2e/deploy/deploy.go
- test/e2e/deploy/operator.go
> Repair deployments

- go.mod
- go.sum
- test/e2e/deploy/deploy.go
- test/e2e/deploy/volumeleaks.go
- test/e2e/storage/csi_volumes.go
- test/e2e/storage/sanity.go
- test/e2e/storage/scheduler/scheduler.go
- test/setup-deployment.sh
- test/start-kubernetes.sh
- test/test.make
This merges PR #604 into the operator branch.
> operator: E2E fixes

- pkg/pmem-csi-driver/nodeserver.go
- test/e2e/storage/sanity.go
Several fixes and tests for ephemeral inline volumes.
> idempotent ephemeral volumes

- pkg/pmem-csi-operator/controller/deployment/controller_driver.go
- pkg/pmem-csi-operator/pmem-tls/tls.go
Reset the memory of private keys and certificates after use. Also
initiating garbage collection of these variables manually so that could
avoid minimize the attack surface.
Go memory management is transparent and have very limited access to
programmer, here we do our best-efforts to zeroing the memory.
Also changed the default RSA key size to 3072 bits.
> operator: zeroing memory of keys and certificate variables

- .github/workflows/publish.yml
- README.md
This is in preparation for 0.7.x.
Has been tested in my repo:
- https://pohly.github.io/pmem-CSI/0.7/ (slightly older content, for testing purposes)
- https://pohly.github.io/pmem-CSI/latest/
> release docsite

- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
Minor fixes to how we handle incoming HTTP requests.
> webhook cleanup

- Jenkinsfile
Let's see whether we can parallelize the long-running test steps...
If exporting images and restoring the right environment on the other workers is fast enough, this should be worthwhile.
> Jenkins parallel

- test/check-imagefile.sh
- test/e2e/deploy/cluster.go
- test/e2e/deploy/deploy.go
- test/e2e/operator/deployment_api.go
- test/e2e/storage/sanity.go
We have issues with unexpected timeouts in the CI. Perhaps this helps.
> wait for driver + VM

- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- test/e2e/deploy/deploy.go
- test/e2e/e2e_test.go
- test/e2e/metrics/metrics.go
- test/e2e/storage/sanity.go
This adds various HTTP and networking related tests.
> input validation

- Jenkinsfile
The reason is that we have seen several random test failures in our CI
that only occurred on Clear Linux. This is slowing down PMEM-CSI
development and often we don't have the knowledge and/or time to solve
these issues.
Clear Linux was used to cover Kubernetes 1.17. This now gets tested on
Fedora. PR testing now also happens 1.15, which is more useful than
testing on Clear Linux because we cover the full range of supported
Kubernetes releases; this would have caught the recent issue with the
operator on Kubernetes 1.15 much earlier.
What we loose in the cI is testing with crio. This shouldn't matter
that much because (at least conceptually) PMEM-CSI has no dependency
on the container runtime.
> CI: replace Clear Linux testing with Fedora

- pkg/apis/pmemcsi/v1alpha1/deployment_types.go
- pkg/deployments/load.go
- pkg/deployments/load_test.go
- pkg/pmem-csi-operator/controller/deployment/controller_driver.go
- test/e2e/deploy/deploy.go
- test/e2e/e2e.go
- test/e2e/operator/deployment_api.go
- test/e2e/operator/validate/validate.go
- test/start-operator.sh
Several fixes and one test enhancement.
Fixes: #660
> Operator deployment fixes

- pkg/pmem-csi-driver/nodeserver.go
- test/e2e/storage/sanity.go
Caching volume information of pre-published volumes could be error prone
on node driver restart. Instead, we could rebuild this information by
looking into existing mounts.
FIXES #502
> pmem-csi-driver: avoid caching pre-mounted volume information

- README.md
This will show a static image that can be clicked on to play the
animated version. We could embed the player
script (https://asciinema.org/docs/embedding) but this may be
overkill.
Fixes: https://github.com/intel/pmem-csi/issues/664
> docs: asciinema demo with thumnail preview

- Jenkinsfile
> Fix release 0.7

- docs/install.md
> docs: fix typo in the installation documentation

- test/e2e/operator/deployment_api.go
In case operator failed to create sub-resources due to conflicts on a
deployment, shall recover that failed deployment automatically
once after the conflicts got resolved. Added a e2e test for covering
this.
FIXES: #618
> operator: test for deployment recovery from conflicts

- test/setup-deployment.sh
There's no such thing as a "pmem-csi driver persistent volume", and
capitalization isn't up-to-date. Let's make it clear that this is
about trying out the "PMEM-CSI driver" with different kinds of
volumes.
> test: fix usage instructions

- docs/install.md
- test/setup-deployment.sh
Both are relevant for PMEM-CSI 0.7.x.
> backport doc changes

- pkg/deployments/load.go
- pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go
These changes came out of back-porting PR #708 
They are also included in https://github.com/intel/pmem-csi/pull/712 for release-0.7.
> operator deployment testing

- examples/cassandra.md
- examples/memcached.md
- examples/readme.rst
> Example docs: Cassandra + KubeDB operator

- test/setup-deployment.sh
Sometimes when quickly deleting a deployment and recreating it,
Kubernetes rejects a service with
nodePort: Invalid value: 32000: provided port is already allocated
Kubernetes 1.19 might be a bit better in this regard, but it's unclear
whether this really addresses the issue in our case and we also need
to work with older releases, so we emulate the behavior of an operator
and retry until it succeeds.
Because the error might really be permanent, we time out after one
minute.
> deploy: retry after node port reuse error

- pkg/pmem-csi-operator/controller/deployment/controller_driver.go
- pkg/pmem-csi-operator/controller/deployment/deployment_controller.go
- pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go
Update fails if there is any mismatch in resource revision due to
intermediate updates to that deployment. Then the operator has to get
fresh copy and update status on that revision. Instead, we can use
patch.
The same observed in CI test failure:
```
deployment_controller.go:172] failed to update status "Running" for deployment "pmem-csi-with-defaults": Operation cannot be fulfilled on deployments.pmem-csi.intel.com "pmem-csi-with-defaults": the object has been modified; please apply your changes to the latest version and try again
```
> operator: patch deployment status instead of update

- deploy/bindata_generated.go
- deploy/kubernetes-1.17/direct/testing/pmem-csi.yaml
- deploy/kubernetes-1.17/lvm/testing/pmem-csi.yaml
- deploy/kubernetes-1.17/pmem-csi-direct-testing.yaml
- deploy/kubernetes-1.17/pmem-csi-lvm-testing.yaml
- deploy/kubernetes-1.18/direct/testing/pmem-csi.yaml
- deploy/kubernetes-1.18/lvm/testing/pmem-csi.yaml
- deploy/kubernetes-1.18/pmem-csi-direct-testing.yaml
- deploy/kubernetes-1.18/pmem-csi-lvm-testing.yaml
- deploy/kubernetes-1.19-alpha/direct/testing/pmem-csi.yaml
- deploy/kubernetes-1.19-alpha/lvm/testing/pmem-csi.yaml
- deploy/kubernetes-1.19-alpha/pmem-csi-direct-testing.yaml
- deploy/kubernetes-1.19-alpha/pmem-csi-lvm-testing.yaml
- deploy/kubernetes-1.19/direct/testing/pmem-csi.yaml
- deploy/kubernetes-1.19/lvm/testing/pmem-csi.yaml
- deploy/kubernetes-1.19/pmem-csi-direct-testing.yaml
- deploy/kubernetes-1.19/pmem-csi-lvm-testing.yaml
- deploy/kustomize/testing/socat.yaml
- test/e2e/deploy/cluster.go
- test/e2e/deploy/deploy.go
- test/e2e/metrics/metrics.go
- test/e2e/operator/deployment_api.go
- test/e2e/storage/sanity.go
- test/setup-fedora-govm.sh
This builds on top of https://github.com/intel/pmem-csi/pull/738 and adds commits that may address the sanity test connection issues.
> debug connection issues

- test/e2e/deploy/deploy.go
- test/setup-fedora-govm.sh
We didn't lock down the containerd version, which caused cluster
startup to fail when containerd was updated to 1.3.7 and the
configuration format changed.
> test: update docker + containerd

- pkg/pmem-csi-operator/controller/deployment/controller_driver.go
- pkg/pmem-csi-operator/controller/deployment/deployment_controller.go
With the recent commit 761d7cef0b96ea3e2ed559c5e89e7f918b2112b9, the
spec changes made to a deployment are get reverted and not been saved
even in the deployment cache. But when we compare this cached object
against the new deployment (with defaults set) result those default
fields as changes.
This could be fixed by resetting those defaults to cached deployment
before comparison.
Also removed unneeded deep copy of deployment object while passing to
client.MergeFrom().
> operator: Fix issue in deployment comparison

- docs/install.md
We have most of the information documented already, but admins may
need some additional guidance on where to start and what's expected of
them. The new section also spells out some dos and don'ts.
Fixes #312, #707
> docs: introduction section for admins

- test/e2e/deploy/deploy.go
- test/start-operator.sh
- test/test-config.sh
> test deployment fixes and cleanup

- conf.json
- docs/static/override.css
Rebased to resolve conflicts. Replaces PR #769
> Fixes color of verbatim links.

- conf.py
Fixes: #767 
Signed-off-by: Kevin Putnam <kevin.putnam@intel.com>
> Documentation: Adds load of override.css to conf.py

- deploy/kustomize/metrics-server/kustomization.yaml
- deploy/kustomize/vpa-for-pmem-csi/kustomization.yaml
- deploy/kustomize/vpa-for-pmem-csi/vpa-controller.yaml
- deploy/kustomize/vpa-for-pmem-csi/vpa-node.yaml
- docs/DEVELOPMENT.md
- hack/setup-va.sh
This is useful for replacing the guessed default resource requirements
in the operator.
> measure resource consumption with Vertical Pod Autoscaler

- pkg/pmem-csi-operator/controller/deployment/controller_driver.go
- pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go
- test/e2e/operator/deployment_api.go
`DriverDeployed` and `CertsVerified` in case of verification failure
status conditions were missing.
Also added conditions validation in unit tests.
FIXES #819
> operator: Add missing deployment status conditions.

- test/start-kubernetes.sh
Current default fedora(31) seems not supported(?):
```
Downloading https://download.fedoraproject.org/pub/fedora/linux/releases/31/Cloud/x86_64/images/Fedora-Cloud-Base-31-1.9.x86_64.raw.xz image
[2020-12-03T11:09:41.461Z] curl: (22) The requested URL returned error: 404
```
Hence moving to the latest release. Had to use 'grubby' for modifying the
kernel parameters.
> test cluster: Move to fedora-33 cloud image

- deploy/crd/pmem-csi.intel.com_deployments.yaml
- deploy/crd/pmem-csi.intel.com_deployments_webhook.yaml
- docs/install.md
- pkg/apis/pmemcsi/v1alpha1/deployment_conversion.go
- pkg/apis/pmemcsi/v1alpha1/deployment_types.go
- pkg/apis/pmemcsi/v1beta1/deployment_types.go
- test/e2e/deploy/operator.go
- test/e2e/operator/deployment_api.go
This includes https://github.com/intel/pmem-csi/pull/830 (validation, defaulting and conversion) and garbage collection.
Fixes: #831
> even more operator fixes

- docs/install.md
> doc: a warning note about delete operator

- test/e2e/operator/deployment_api.go
There is a possible race condition on 'evWatcher' map between
accessing/updating map elements and the map deletion:
```
[2021-01-23T02:00:22.076Z] Jan 23 02:00:21.862: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
[2021-01-23T02:00:22.076Z] panic: assignment to entry in nil map
[2021-01-23T02:00:22.076Z]
[2021-01-23T02:00:22.076Z] goroutine 1756272 [running]:
[2021-01-23T02:00:22.076Z] github.com/intel/pmem-csi/test/e2e/operator.glob..func2.1.1(0xc0007cc080, 0xc0000b90f8)
[2021-01-23T02:00:22.076Z] 	/mnt/workspace/pmem-csi_PR-860/test/e2e/operator/deployment_api.go:106 +0x20b
[2021-01-23T02:00:22.076Z] created by github.com/intel/pmem-csi/test/e2e/operator.glob..func2.1
[2021-01-23T02:00:22.076Z] 	/mnt/workspace/pmem-csi_PR-860/test/e2e/operator/deployment_api.go:99 +0x873 …
```
> operator/test: fix race condition in events handling

- pkg/pmem-csi-operator/controller/deployment/controller_driver.go
- pkg/pmem-csi-operator/controller/deployment/deployment_controller.go
- pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go
Fixes: https://github.com/intel/pmem-csi/issues/852
> Operator race condition

- operator/operator.make
> operator: drop using forked repo

- test/e2e/operator/validate/validate.go
This was needed when validating secrets generated by the operator. We
no longer do that and thus the code can be removed.
> test: remove unused code

- docs/install.md
- pkg/scheduler/scheduler.go
- test/e2e/deploy/deploy.go
This adds new metrics data (useful for admins) and uses that to validate a driver's functionality (useful for us).
> Wait for mutating webhook

- test/e2e/operator/validate/validate.go
- test/e2e/storage/csi_volumes.go
- test/e2e/storage/immediatebinding.go
- test/e2e/storage/provisioning.go
- test/test.make
This is an attempt to trigger issue #878. Even if the test just passes, having it is worthwhile to prevent regressions.
> Immediate binding

- README.md
Minor changes; added attribution for Docker, changed sentence syntax, used active voice.
Signed-off-by: DougTW <doug.martin@intel.com>
> Edited root readme.

- test/e2e/metrics/metrics.go
- test/e2e/tls/tls.go
This tries to address several test flakes via retries.
Fixes: #841
Fixes: #888 
Fixes: #901
> Test flakes

- Jenkinsfile
- test/e2e/deploy/volumeleaks.go
ssh error was checked, but only to detect end of nodes.
It is also possible ssh fails for some other reason,
so try to detect and log this. Retry once.
> Volume leaks test: better check for ssh error and retry

- docs/DEVELOPMENT.md
Standardized line lengths to 78 chars, added Trademark and Branding disclaimers, made minor edits (spelling, grammar, sentence syntax, made capitalization consistent).
> Edited DEVELOPMENT.md

- docs/DEVELOPMENT.md
This addresses some nits found during review of
https://github.com/intel/pmem-csi/pull/921
> docs: followup changes for DEVELOPMENT.md

- pkg/pmem-csi-driver/nodeserver.go
- test/e2e/storage/sanity.go
This is WIP as it needs a change on testing code side which fixes repeating of idempotency testing.
The current changes are result of improvements I made during debugging an issue
that occured thanks to kubelet repeating PublishVolume requests, which
seems happens due to some kubelet internal issue.
----
The check for existing file system before mkfs was made on
one call path only, but ephemeral took another path when creating
an inline volume. Due to 2 additional side effects: incomplete
idempotency testing, and issue in kubelet that caused repeated
publishVolume requests, it was exposed that nodeserver attempts
to mkfs a device with existing file system, which fails,
and there is no useful error information.
The use of dax=always allows comparing of mount flags to work
correctly, as …
> nodeserver: Improve idempotency in ephemeral volume creation

- docs/design.md
- pkg/pmem-csi-driver/nodeserver.go
- test/cmd/pmem-access-hugepages/main.go
- test/e2e/storage/dax/dax.go
Give additional options to mkfs.ext4 and mkfs.xfs.
> Create filesystem with 2MB aligned and sized block allocations

- operator/operator.make
> operator: set the generated bundle channel name to 'stable'

- .gitignore
- Makefile
- README.md
- conf.json
- conf.py
- docs/DEVELOPMENT.md
- docs/autotest.md
- docs/design.md
- docs/install.md
- docs/sphinx_ext/linkcheck.py
- docs/sphinx_ext/linkcheck2.py
- examples/gce.md
- examples/memcached.md
We want to check links to detect stale external links and anchors that we didn't get right or that changed.
> docs links check

- pkg/ndctl/region.go
This is crucial for investigating errors like this:
I0623 15:53:24.496027       1 region.go:227] "CreateVolume/ndctl-CreateDevice/CreateNamespace: Creating namespace with requested size" request-counter=9 volume-name="pvc-d4b4db1c-ae61-401b-b2f1-f895ddb1df65" volume-id="pvc-d4-4ed62383608bf88e8948ff07f9c3829217b54e0ca80ff0eb02087dac" region="region0" region-align="1" namespace-align="2Mi" common-align="2Mi" available="896Mi" size="100Mi"
E0623 15:53:24.535748       1 tracing.go:28] "CreateVolume: gRPC call failed" err="rpc error: code = Internal desc = device creation failed: Failed to set namespace size: Invalid argument" request-counter=9
While it doesn't explain the error in this case, at least the relevant
information is available.
> pmem-csi-driver: always log namespace parameters during creation

- Jenkinsfile
Piping the output of the test command into other commands caused the
return code of the "make test_e2e" command to get lost, with the
result that the test was considered "unstable" (because of recorded
JUnit failures) instead of "failed" and later stages like publishing
images ran although they should have been skipped.
Also, the 2>&1 redirection probably was in the wrong place, with the
result that stderr was not filtered.
This is using a minimally intrusive solution where bash is selected
as interpreter by adding it at the start of the sh parameter, then
using pipefail.
This whole script probably should be rewritten with multiline strings,
but a naive attempt at that ended with several hours of trying
different syntax variants and still no success...
> CI: fix suppression of 'make test_e2e' return code

- pkg/pmem-device-manager/pmd-lvm.go
- test/e2e/deploy/pmem.go
- test/e2e/storage/conversion.go
- test/e2e/storage/sanity.go
Fixes: https://github.com/intel/pmem-csi/issues/1012
and some other issue discovered while writing a test.
> LVM namespace setup

- conf.json
- pkg/pmem-csi-operator/controller/deployment/controller_driver.go
- test/e2e/versionskew/operator.go
- test/e2e/versionskew/versionskew.go
- test/test.make
Re-enabling the version skew tests and running tests manually showed that there were some issues.
> Fix version skew

- .github/workflows/publish.yml
- README.md
- conf.json
- hack/merge-release.sh
The v1.0.0 image is public, let's document the new release.
> Release 1.0 docs

- deploy/kustomize/olm-catalog/bases/pmem-csi-operator.clusterserviceversion.yaml
- docs/DEVELOPMENT.md
- Moved operator capabilities to 'Full Lifecycle'.
- Updated the operator release documentation with the new operatorhub repository.
> OperaotorHub changes

- docs/autotest.md
Signed-off-by: Doug Martin <doug.martin@intel.com>
> autotest.md: added trademark disclaimers

- .github/workflows/lint.yaml
- pkg/imagefile/imagefile_test.go
- pkg/ndctl/fake/ndctl.go
- pkg/ndctl/fake/region.go
- pkg/ndctl/ndctl.go
- pkg/pmem-csi-driver/nodeserver.go
- pkg/pmem-csi-driver/pmem-csi-driver.go
- pkg/pmem-csi-operator/controller/deployment/controller_driver.go
- pkg/pmem-csi-operator/controller/deployment/deployment_controller.go
- pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go
- pkg/scheduler/scheduler_test.go
- pkg/volumepathhandler/volume_path_handler.go
- test/cmd/pmem-access-hugepages/main.go
- test/e2e/driver/driver.go
This removes dead or unused code. Found with golangci-lint.
> dead code removal

- Dockerfile
- Jenkinsfile
- Makefile
- deploy/common/pmem-storageclass-ext4-fileio.yaml
- deploy/common/pmem-storageclass-xfs-fileio.yaml
- deploy/kustomize/patches/usage-fileio.yaml
- deploy/kustomize/storageclass-ext4-fileio/kustomization.yaml
- deploy/kustomize/storageclass-xfs-fileio/kustomization.yaml
- docs/install.md
- pkg/pmem-csi-driver/controllerserver-node.go
- pkg/pmem-csi-driver/nodeserver.go
- pkg/pmem-csi-driver/parameters/parameters.go
- pkg/pmem-csi-driver/parameters/parameters_test.go
- pkg/pmem-device-manager/pmd-fake.go
- pkg/pmem-device-manager/pmd-lvm.go
- pkg/pmem-device-manager/pmd-manager.go
- pkg/pmem-device-manager/pmd-manager_test.go
- pkg/pmem-device-manager/pmd-ndctl.go
- test/e2e/driver/driver.go
- test/e2e/storage/csi_volumes.go
- test/e2e/storage/dax/dax.go
- test/e2e/storage/immediatebinding.go
- test/e2e/storage/pmem_csi.go
- test/start-stop-olm.sh
This may be useful for certain classes of applications.
Fixes: https://github.com/intel/pmem-csi/issues/991
> support traditional file IO

- docs/screencast-pmem.sh
This script will create an asciinema recording to show users
how to use the PMEM-CSI operator and drivers along with a
sample application deployed from the PMEM-CSI GitHub.
Signed-off-by: Eric Adams <eric.adams@intel.com>
> docs: Add screencast recording script

- test/e2e/deploy/deploy.go
Top-level nodes were still getting
randomized (https://github.com/onsi/ginkgo/issues/966#issuecomment-1110046593).
> test: run OLM tests first, III
